### ISSUE TITLE
Feature: Select program to run

### ISSUE THREAD

**Issue by robbinonline** [humbertogontijo/homeassistant-roborock#10]
I love this integration first thanks a lot for al the effort.
Can you please make an option to choose what program to run: for example Vacuum & Mop or just mop etc. 

![IMG_1619](https://user-images.githubusercontent.com/660835/207049225-32138024-cf04-453d-ab47-19a96bc3c2f0.PNG)

**Comment by JoramHhub** [comment]
I'd love this option too!

**Comment by manzanita0412** [comment]
Same here! I wonder if room selection could be added too 🤔

**Comment by robbinonline** [comment]
I think it's possible:

https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/422

**Comment by CalamarBicefalo** [comment]
Hello humberto, this extension is great, thank you very much!
> The mop option is not supported in the xiaomi Lovelace card as far as I know. The room cleaning is already working, just use the "send_command" platform and rename the id for each room from text to numeric(remove the quotes)

Would it be possible to document that somewhere?

**Comment by kristofferR** [comment]
> Hello humberto, this extension is great, thank you very much!
> 
> > The mop option is not supported in the xiaomi Lovelace card as far as I know. The room cleaning is already working, just use the "send_command" platform and rename the id for each room from text to numeric(remove the quotes)
> 
> Would it be possible to document that somewhere?

https://github.com/humbertogontijo/homeassistant-roborock/issues/20#issuecomment-1351719468

**Comment by CalamarBicefalo** [comment]
> > Hello humberto, this extension is great, thank you very much!
> > > The mop option is not supported in the xiaomi Lovelace card as far as I know. The room cleaning is already working, just use the "send_command" platform and rename the id for each room from text to numeric(remove the quotes)
> > 
> > 
> > Would it be possible to document that somewhere?
> 
> [#20 (comment)](https://github.com/humbertogontijo/homeassistant-roborock/issues/20#issuecomment-1351719468)

Thank you very much

**Comment by notorioustubze** [comment]
> The mop option is not supported in the xiaomi Lovelace card as far as I know. The room cleaning is already working, just use the "send_command" platform and rename the id for each room from text to numeric(remove the quotes)

Hi, firstly thank you! Your work is amazing. I'm looking at setting up individual room cleaning, would you mind elaborating on your above comment. I've found the "send_command" option but unsure where I would adjust the numeric value. TIA
<img width="1143" alt="Screenshot 2022-12-20 at 10 49 52" src="https://user-images.githubusercontent.com/53260708/208649513-ad6a987e-80cf-4cd4-963c-2f67189185be.png">

**Comment by robbinonline** [comment]
Found it out:

**Comment by humbertogontijo** [comment]
I've added these mopping mode and intensity mapping as an attribute to the vacuum entity to be shown in the card(Just english, no translation at this time)

**Comment by robbinonline** [comment]
For now I have created this card. 
This card includes 3x a different input_select linked to 3 automations. 

<img width="532" alt="Scherm­afbeelding 2022-12-21 om 11 31 24" src="https://user-images.githubusercontent.com/660835/208884441-1277e1d3-7069-46e5-9a90-3aa3e9b1b6ca.png">

Example input select:
`
input_select:
  vacuumscrubintensity:
    options:
      - Off
      - Mild
      - Moderate
      - Intense
    icon:mdi:water
`

**Comment by manzanita0412** [comment]
> 

Sorry if this is a dumb question, but how did you make that custom card? It looks great!

**Comment by robbinonline** [comment]
> Sorry if this is a dumb question, but how did you make that custom card? It looks great!

@manzanita0412 

With a custom card vertical-stack-in-card

**Comment by kristofferR** [comment]
> > Sorry if this is a dumb question, but how did you make that custom card? It looks great!
> 
> @manzanita0412
> 
> With a custom card vertical-stack-in-card

Can you please share the code for that card?

**Comment by humbertogontijo** [comment]
There are services to do this now. Setting mop mode to off will only vacuum, and setting the fan speed to off will only mop. Setting both to other value than off will do both

**Comment by manzanita0412** [comment]
> There are services to do this now. Setting mop mode to off will only vacuum, and setting the fan speed to off will only mop. Setting both to other value than off will do both

@humbertogontijo , I don't see the fan speed service as something that can be called explicitly:

![image](https://user-images.githubusercontent.com/36706403/210484204-0247def4-cc4e-4d2f-85d1-8ebd3d00e2c7.png)
