### ISSUE TITLE
Map not loading 

### ISSUE THREAD

**Issue by lucaobermaier** [humbertogontijo/homeassistant-roborock#102]
After updating to 0.0.20 the map is not loading any more.
Yesterday - i think i ran on 0.0.16 everything was fine.
Home Assistant 2022.12.9
Supervisor 2022.12.1
Operating System 9.4
Roborock S5 Max

**Comment by adekloet** [comment]
#101 #98 are both open because the map is not / or takes a long time to import as camera.

**Comment by polysa** [comment]
> After updating to 0.0.20 the map is not loading any more. Yesterday - i think i ran on 0.0.16 everything was fine. Home Assistant 2022.12.9 Supervisor 2022.12.1 Operating System 9.4 Roborock S5 Max

Had the same problem. After updating the integration make sure to click the configure button under "Devices & Services" and save. Then reload the integration.

The map will load again!

**Comment by lucaobermaier** [comment]
> > After updating to 0.0.20 the map is not loading any more. Yesterday - i think i ran on 0.0.16 everything was fine. Home Assistant 2022.12.9 Supervisor 2022.12.1 Operating System 9.4 Roborock S5 Max
> 
> Had the same problem. After updating the integration make sure to click the configure button under "Devices & Services" and save. Then reload the integration.
> 
> The map will load again!

WORKS!
