### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by rosskyl** [humbertogontijo/homeassistant-roborock#104]
I'm having an issue when trying to setup. I updated from version .1 to .2 and missed the documentation for issues with setup and removed my integration and tried re-adding it. I get the error below.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 84, in async_setup_entry
    translation = get_translation(hass)
  File "/config/custom_components/roborock/__init__.py", line 42, in get_translation
    language = hass.config.language
AttributeError: 'Config' object has no attribute 'language`

**Comment by humbertogontijo** [comment]
No language in your HA config? That's new. I'll default it to English for these scenarios

**Comment by rosskyl** [comment]
Yes looking at docs it looks like this is optional and defaults to EN. I'm not sure why mine is blank.

**Comment by humbertogontijo** [comment]
I just released version 0.0.21 to fix this
