### ISSUE TITLE
Map unavailable in 0.0.20

### ISSUE THREAD

**Issue by evnvc** [humbertogontijo/homeassistant-roborock#105]
Getting a map loading error on the latest version, tried reloading the integration, restarting same result. All other sensors seem fine:
`This entity is no longer being provided by the roborock integration. If the entity is no longer in use, delete it in settings.`
I'm using the integration with a Roborock S7

**Comment by silkw0rm** [comment]
Same issue and message here.

Using Roborock S5

**Comment by yolani** [comment]
Same here with S6, also "Water shortage" sensor is unavailable

**Comment by humbertogontijo** [comment]
Make sure to click the configure button under "Devices & Services" and save. Then reload the integration.

**Comment by humbertogontijo** [comment]
I need some logs to investigate your issue with the water shortage sensor

**Comment by lucaobermaier** [comment]
I already wrote a comment but its not existing any longer.
Regarding the map issue - after changing the map rotation its not possible to return to 0°

**Comment by silkw0rm** [comment]
Thank you. The map became available again after going to Configure, clicking Submit and then reloading the integration.

**Comment by hheimbuerger** [comment]
Can someone please clarify what kind of `Configure` button y'all are talking about?

Could someone post a screenshot of that button, please?
