### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'language'

### ISSUE THREAD

**Issue by carlerikssons** [humbertogontijo/homeassistant-roborock#106]
Integration failed to setup

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/roborock/__init__.py:42
Integration: Roborock (documentation, issues)
First occurred: 15:31:44 (2 occurrences)
Last logged: 15:31:55

Error setting up entry xxx@xxx.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 84, in async_setup_entry
    translation = get_translation(hass)
  File "/config/custom_components/roborock/__init__.py", line 42, in get_translation
    language = hass.config.language
AttributeError: 'Config' object has no attribute 'language'

Roborock FW: 02.61.86 
Home Assistant 2022.9.2
Supervisor 2022.12.1
Operating System 8.5
Frontend 20220907.0 - latest

I have following versions with the same problem. 
0.0.16 - 0.0.20

**Comment by humbertogontijo** [comment]
I just released a version 0.0.21 to fix this

**Comment by carlerikssons** [comment]
thanks, it works now!
