### ISSUE TITLE
Map unavailable 

### ISSUE THREAD

**Issue by Sagi-bb** [humbertogontijo/homeassistant-roborock#108]
Since previous version map always unavailable. restart doesn't help.
Last update 0.0.21 doesn't solve this.

![image](https://user-images.githubusercontent.com/68748153/210641262-4cb3c84f-03b7-40a2-8159-0c6358fe0c9e.png)

**Comment by Brian-lub** [comment]
You need to configure the integration again and the de a reload, then it works

**Comment by Sagi-bb** [comment]
working thank you !!!!
I also noticed some sensors unavailable ?
where they removed ? should i delete them or it will be fixed ?
![image](https://user-images.githubusercontent.com/68748153/210755786-d3182131-5ade-4c9d-a201-1b0e7b2109e7.png)
![image](https://user-images.githubusercontent.com/68748153/210755828-a84ee876-bc05-4837-8b3b-db7919eec088.png)

**Comment by Nipal33** [comment]
Thank you Brian, it helped me as well :)

On my map though, I can see 2 errors in the rooms. I don't know if they are actual errors or if the rooms are just with the same color maybe.
I'll try and test it this weekend.

**Comment by humbertogontijo** [comment]
It is fixed in the latest version.
About the sensor which the name ends with "left" they were renamed to "remaining" so you can delete the old ones

**Comment by Sagi-bb** [comment]
OK i see thank you
