### ISSUE TITLE
Possibility to upstream this?

### ISSUE THREAD

**Issue by T4cC0re** [humbertogontijo/homeassistant-roborock#11]
Hi!

I have just come across this. Amazing! I can finally use the Roborock app (for advanced features) and still use HomeAssistant. So thank you very much for this!

I was just wondering whether the API for Roborock and Mi Home are too different for it to be possible to merge the efforts of this integration with the [Xiaomi one](https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_miio)? Considering when I switched between the Roborock app and the Mi Home app, my robot's maps were still there, so I am curious if they might be using the exact same (or very similar) backend, just with different endpoints and authentication methods?

This might make it easier to maintain the integration in the future when developments made for the Roborock API could be joined with the Xiaomi Integration. So they would benefit from each other.

**Comment by humbertogontijo** [comment]
Hey. Since the authentication method and the communication are different I just thought that creating a new integration would be the easiest way. But the commands are still the same. Anyway, they are welcome to use this code base into their repo

**Comment by bdr99** [comment]
It would be great if this integration could be added to HA core, that way more users would be aware of its existence. I only happened to come across it by chance during a google search.

@humbertogontijo I don't have a Roborock vacuum, but I've created two integrations that were merged into HA core. If you have any interest in getting this one merged, I'd be willing to assist with preparing things. The code quality standards are a bit higher for core integrations, but there is lots of info in the developer docs: https://developers.home-assistant.io/docs/development_checklist/

The first step would be to move the API code into a separate library and publish it to PyPI.

**Comment by Lash-L** [comment]
There is a PR for adding it to core:

https://github.com/home-assistant/core/pull/89456

If you're a programmer feel free to give it a review. If you're not - feel free to give it a emoji reaction so that core devs know there is interest! Please don't comment unless you are reviewing though!
