### ISSUE TITLE
Missing info in frontend 

### ISSUE THREAD

**Issue by Brian-lub** [humbertogontijo/homeassistant-roborock#110]
![image](https://user-images.githubusercontent.com/47833231/210644823-ddb540de-e9c9-456c-940e-8b83f78a4632.png)
Roborock S6 MaxV
i have been un able to get all the info in this frontend integration i had before i switched to this integration, is properly something i am overlooking, but i need some help seeing what i am doing wrong.
Before i got the maintenance info in the Xiaomi Vacuum Map Card, and i see others have that too.

**Comment by medfiras** [comment]
you can take a look at #79 on [this](https://github.com/humbertogontijo/homeassistant-roborock/issues/79#issuecomment-1368458016) or [this](https://github.com/humbertogontijo/homeassistant-roborock/issues/79#issuecomment-1371953352)
