### ISSUE TITLE
Roborock S6 Pure

### ISSUE THREAD

**Issue by JochenV1976** [humbertogontijo/homeassistant-roborock#115]
Hello,

I've installed the roborock integration, and I managed to get my Roborock S6 Pure into HA.
At first sight, there are 2 issues:
* When the roborock is cleaning, the map stays idle, so there is no 'live' view on where the roborock is cleaning.
![roborock](https://user-images.githubusercontent.com/80390867/210777240-6a916e4b-c122-44cc-b0d3-de2226141dd8.jpg)
* I don't have the possibility to clean a single room, which is created in the roborock app.

Any idea's how to solve these points?

Thanks in advance!

**Comment by medfiras** [comment]
- for the first point (the map stays idle) i think it's the same #69 
- for the second point, i'm using `type: custom:xiaomi-vacuum-map-card` and i can do it 

![image](https://user-images.githubusercontent.com/1859595/210937376-8bd028c3-8d6c-449a-b343-1bc5afb5f9ab.png)

**Comment by viv-design** [comment]
I'm missing the rooms option too im using type: custom:xiaomi-vacuum-map-card as well with a Roborock S6 MaxV. Can you share your card yaml to see if there is anything I'm missing. Thanks

**Comment by viv-design** [comment]
I figured it out, you need to run "generate map config"

**Comment by Lash-L** [comment]
Looks like this is resolved - so I'm closing it
