### ISSUE TITLE
Missing sensor: total clean count

### ISSUE THREAD

**Issue by Dis90** [humbertogontijo/homeassistant-roborock#117]
Hi,

Thanks for this integration. For some reason there's no sensor for total clean count. Information is available in app.
I have Roborock S6 Pure.

Log:

> root@homeassistant:/usr/share/hassio/homeassistant# tail -f home-assistant.log
> 2023-01-05 16:24:19.646 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the CleanRecordField.AREA as the initial value is None
> 2023-01-05 16:24:19.646 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the CleanSummaryField.CLEAN_TIME as the initial value is None
> 2023-01-05 16:24:19.646 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the CleanSummaryField.CLEAN_AREA as the initial value is None
> 2023-01-05 16:24:19.646 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the CleanSummaryField.CLEAN_COUNT as the initial value is None
> 2023-01-05 16:24:19.646 DEBUG (MainThread) [custom_components.roborock.sensor] It seems the roborock.vacuum.a08 does not support the CleanSummaryField.DUST_COLLECTION_COUNT as the initial value is None
> 2023-01-05 16:24:19.661 DEBUG (MainThread) [custom_components.roborock.camera] Retrieving map from Roborock MQTT
> 2023-01-05 16:24:19.661 DEBUG (MainThread) [custom_components.roborock.api.api] id=5 Requesting method get_map_v1 with None
> 2023-01-05 16:24:19.832 DEBUG (MainThread) [custom_components.roborock.api.api] id=5 Response from get_map_v1: 33088 bytes
> 2023-01-05 16:24:19.921 DEBUG (MainThread) [custom_components.roborock.camera] Map data retrieved
> 2023-01-05 16:24:19.921 DEBUG (MainThread) [custom_components.roborock.camera] Map is ok
> 2023-01-05 16:24:49.072 DEBUG (MainThread) [custom_components.roborock.api.api] id=6 Requesting method get_status with None
> 2023-01-05 16:24:49.073 DEBUG (MainThread) [custom_components.roborock.api.api] id=7 Requesting method get_dnd_timer with None
> 2023-01-05 16:24:49.076 DEBUG (MainThread) [custom_components.roborock.api.api] id=8 Requesting method get_clean_summary with None
> 2023-01-05 16:24:49.078 DEBUG (MainThread) [custom_components.roborock.api.api] id=9 Requesting method get_consumable with None
> 2023-01-05 16:24:49.203 DEBUG (MainThread) [custom_components.roborock.api.api] id=7 Response from get_dnd_timer: {'start_hour': 22, 'start_minute': 0, 'end_hour': 8, 'end_minute': 0, 'enabled': 1}
> 2023-01-05 16:24:49.207 DEBUG (MainThread) [custom_components.roborock.api.api] id=6 Response from get_status: {'msg_ver': 2, 'msg_seq': 1984, 'state': 8, 'battery': 100, 'clean_time': 1497, 'clean_area': 26857500, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0, 'in_fresh_state': 1, 'lab_status': 3, 'water_box_status': 0, 'fan_power': 103, 'dnd_enabled': 0, 'map_status': 3, 'is_locating': 0, 'lock_status': 0}
> 2023-01-05 16:24:49.241 DEBUG (MainThread) [custom_components.roborock.api.api] id=8 Response from get_clean_summary: 109286
> 2023-01-05 16:24:49.244 DEBUG (MainThread) [custom_components.roborock.api.api] id=9 Response from get_consumable: {'main_brush_work_time': 110283, 'side_brush_work_time': 110283, 'filter_work_time': 110283, 'filter_element_work_time': 0, 'sensor_dirty_time': 109286}
> 2023-01-05 16:24:49.245 DEBUG (MainThread) [custom_components.roborock] Finished fetching roborock data in 0.173 seconds (success: True)

**Comment by medfiras** [comment]
i'm using S7Max and it's availble 

![image](https://user-images.githubusercontent.com/1859595/210937037-019fcfd4-b831-4447-ae76-5c305b61775b.png)

**Comment by SVNKoch** [comment]
@medfiras what ui are you using there?

**Comment by medfiras** [comment]
xiaomi-vacuum-map-card [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card)

**Comment by humbertogontijo** [comment]
For S6 MaxV, S7 and S7 MaxV the command get_clean_summary returns a json. I'm not sure how to parse the response: `Response from get_clean_summary: 109286`

**Comment by Dis90** [comment]
I think that is total clean time in seconds because app shows now 33 hours.
This is how it looks on app:

![IMG_2381](https://user-images.githubusercontent.com/1754572/212835879-e3f9e5cc-57f0-4a9b-b98f-f6dfe1d51aa2.PNG)

**Comment by mihalski** [comment]
Is there simple a way I could test these JSON requests?
I could then compare both my S6 MaxV and S6 Pure to the result and verify whether it is in seconds.
Thank you for a great integration.

**Comment by humbertogontijo** [comment]
@mihalski Just add 
```
logger:
  logs:
    custom_components.roborock: debug
```
to your configuration.yaml
