### ISSUE TITLE
Error when calling the set_mop_intensity and set_mop_mode services

### ISSUE THREAD

**Issue by Alindil** [humbertogontijo/homeassistant-roborock#120]
Hi,

When starting home assistant, the set_mop_intensity and set_mop_mode services are working fine. But after a few minutes after the first call, they don't work anymore and we have to restart home assistant. My roborock is an S7 Pro Ultra
<img width="763" alt="roborock" src="https://user-images.githubusercontent.com/30829631/210962846-e9e79c89-8168-44d3-b674-7205f7d13de5.PNG">

**Comment by gvoepel** [comment]
I am having this same exact issue.

**Comment by Maarten112** [comment]
Issue over here is the same! It works about 1 time, thereafter the service gives the same error as issue opener shows in his screenshot.

**Comment by humbertogontijo** [comment]
Fixed in the latest version
