### ISSUE TITLE
Retriveing map when moved over to roborock app, prievously using xioami app

### ISSUE THREAD

**Issue by Ontrackx** [humbertogontijo/homeassistant-roborock#126]
Is there a way to retreive the map from roborock? or am i missing something

camera:
  - platform: xiaomi_cloud_map_extractor
    name: vacuum1
    host: 192.168.86.45
    token: mytoken
    username: email
    password: password
    draw: ['all']
    attributes:
      - calibration_points

**Comment by Xyaren** [comment]
The extractor is not working with the roborock app.
You also don't need it, as the roborock integration should provide a camera entity.

**Comment by Ontrackx** [comment]
Yes reloaded the intrigation and it came up. Wasnt clear in the
instructions.thanks

lør. 7. jan. 2023, 18:30 skrev Tobias G ***@***.***>:

**Comment by Ontrackx** [comment]
solved by reloding intrigation
