### ISSUE TITLE
Error while setting up roborock platform for camera

### ISSUE THREAD

**Issue by robertteir** [humbertogontijo/homeassistant-roborock#127]
Seems to be an issue with the camera after initial install:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/roborock/camera.py", line 56, in async_setup_entry
    image_config = config_entry.options[CONF_MAP_TRANSFORM]
KeyError: 'map_transformation'

Reconfiguring the integration (change map rotation for instance) and the reloading it will fix the issue. Adding an issue since this might cause problems for people when trying to configure the vacuum map card

**Comment by doudz** [comment]
Got the same bug, changing rotation from 0 to 90 and then revert it back to 0 fix the problem
![image](https://user-images.githubusercontent.com/1262548/211154480-733b12f6-222e-4971-aa2c-eeabdb793ed1.png)

**Comment by humbertogontijo** [comment]
This seems to be fixed
