### ISSUE TITLE
[FR] Have the ability to sign in without a password

### ISSUE THREAD

**Issue by desheh** [humbertogontijo/homeassistant-roborock#13]
Hey,

It appears that it's also possible to sign-in to the Roborock cloud with just an email address (and a 2SV code), and without a password.

It's commented out in the [original nodejs script](https://gist.github.com/rovo89/dff47ed19fca0dfdda77503e66c2b7c7) for fetching the token+data from the Roborock cloud like so:

```js
    await loginApi.post('api/v1/sendEmailCode', new url.URLSearchParams({username: username, type: 'auth'}).toString()).then(res => res.data);
    // ... get code from user ...
    userdata = await loginApi.post('api/v1/loginWithCode', new url.URLSearchParams({username: username, verifycode: code, verifycodetype: 'AUTH_EMAIL_CODE'}).toString()).then(res => res.data.data);
```

Thought it could be a nice improvement over the current flow that requires a password.

**Comment by humbertogontijo** [comment]
Hey! Yes, I am aware and it will be used. I'm just focusing on functionality right now. Feel free to open a PR too
