### ISSUE TITLE
Home Assistant Restarts itself When Initiating Room Cleaning from Map

### ISSUE THREAD

**Issue by amathews84** [humbertogontijo/homeassistant-roborock#132]
I am noticing some extremely strange behavior that has been happening very consistently when I initiate a room cleaning from the map entity.  Home Assistant restarts itself and everything is extremely slow to load.  When I checked the logs I see that the Roborock integration itself it is taking a long time to load:

Logger: homeassistant.components.camera
Source: helpers/entity_platform.py:797
Integration: Camera
First occurred: 11:22:44 PM (4 occurrences)
Last logged: 11:30:29 PM

Updating roborock camera took longer than the scheduled update interval 0:00:05

Any idea what could be causing this?

**Comment by carlerikssons** [comment]
I have noted the same problem, but with full cleaning as well. 

Couldn't find anything specific in the logs though, but my ram usage is at 86%. 

Maybe Roborock integration uses a lot of frame when the map is updated?

**Comment by humbertogontijo** [comment]
There was a bug in the previous version with the map processing code(which caused high processor usage). It could be related to this. If it is, its probably fixed in latest version

**Comment by humbertogontijo** [comment]
@amathews84 @carlerikssons Does this problem persist?

**Comment by amathews84** [comment]
No, I have not come across this issue for about a week or so.  I'm currently on v 0.0.22

**Comment by humbertogontijo** [comment]
Closing it then. Feel free to open another if needed
