### ISSUE TITLE
Feature request: Remove one or more devices

### ISSUE THREAD

**Issue by labbs1** [humbertogontijo/homeassistant-roborock#133]
Hi,

First, thanks for a very nice integration!

I have two Roborocks on my account and a third one shared with me. All three are shown in HA which is great but I would like to remove/hide the one at my parents. If I deactivate the device it is still shown. Nothing important but perhaps something that could be implemented in the future ;)

/Labbs

**Comment by humbertogontijo** [comment]
I've added the config option to exclude shared devices with the help of @shred86 in v0.0.27

**Comment by labbs1** [comment]
Great news,
Altough, the integration does not initialize any longer...

Logger: custom_components.roborock
Source: helpers/update_coordinator.py:201
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 12:20:13 (13 occurrences)
Last logged: 12:33:32

Error fetching roborock data: Timeout after 4 waiting for response
Error fetching roborock data: Failed to publish

Logger: custom_components.roborock.api.api
Source: custom_components/roborock/api/api.py:181
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 12:20:20 (4618 occurrences)
Last logged: 12:33:52

Roborock mqtt client disconnected (rc: 7)
Roborock mqtt client disconnected (rc: 2)

**Comment by shred86** [comment]
This appears to be related to #144 

4,618 MQTT disconnects in less than 14 mins is likely causing the Roborock server to temporarily ban you. 

@humbertogontijo obviously something strange going on with the reconnect logic. Just throwing some ideas out there - Could it be related to paho mqtt automatically handling reconnects? In their docs it states: “This call also handles reconnecting to the broker” when using loop_start().

**Comment by humbertogontijo** [comment]
@labbs1 were you using version v0.0.27 while getting these disconnections?

**Comment by labbs1** [comment]
Thanks @humbertogontijo @shred86 

After reconnected my own Roborock I was able to get the integration working again ;)

The App reported it as offline first. Rebooted it and everything was up and running. Sorry for not checking this first but I will keep an eye on it.

**Comment by humbertogontijo** [comment]
Closing as complete. But I'll do something to backoff the retries when robot is disconnected or offline
