### ISSUE TITLE
Failure calling xiaomi_miio/vacuum_clean_zone. Service not found

### ISSUE THREAD

**Issue by borisdelormas** [humbertogontijo/homeassistant-roborock#142]
After defining a zone, when trying to run the Roborock on that zone I've got this message :

![image](https://user-images.githubusercontent.com/1169740/212144475-078c4d30-0552-4f31-9fd7-9e704031607e.png)

Same thing after putting a pinpoint and trying to run to it : "Échec d'appel du service xiaomi_miio/vacuum_goto. Service not found"

**Comment by shred86** [comment]
You're running the wrong service. 😄 That's the service for the Xiaomi Miio integration. For this integration, you should be using `roborock.vacuum_clean_zone`.

**Comment by borisdelormas** [comment]
Thanks, that sound obvious when you point it :)
Is there a card that support the roborock services ?

Thanks for your help!

**Comment by humbertogontijo** [comment]
Just use the Xiaomi Vacuum Map Card and change the services in config from xiaomi_miio to roborock

**Comment by borisdelormas** [comment]
Ok thanks, I think I'm figuring it out.

Thanks a lot !

**Comment by srrsparky** [comment]
Hi

Trying to work out what to change for the map card. This is my current configuration.
`type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s7_maxv_map
calibration_source:
  camera: true
entity: vacuum.roborock_s7_maxv
vacuum_platform: default
title: Wodger Wamjet the Wobot Wacuum`
These are the supported platforms for the card. Which one should I choose?

![image](https://user-images.githubusercontent.com/19926012/214979924-93237154-4e24-4df5-9c14-da1584ca0bb9.png)

**Comment by Xyaren** [comment]
See here: https://github.com/humbertogontijo/homeassistant-roborock/discussions/40

**Comment by srrsparky** [comment]
Thank you
