### ISSUE TITLE
Vacuum go to command not working

### ISSUE THREAD

**Issue by andrzejf1994** [humbertogontijo/homeassistant-roborock#143]
Hi,

when executing _roborock.vacuum_goto_ service vacuum goes in to "goto" mode but always fails.
I tried different x and y coordinates with no success.
When in dock, vacuum is backing up ~20cm and stops.
When not in dock, it stays in place.
Voice communicates and Lidar are working.

Vacuum: Roborock S7 MaxV
Software: 02.56.02

**Comment by humbertogontijo** [comment]
I use the goto service with the xiaomi vacuum map card and it works fine

**Comment by andrzejf1994** [comment]
My bad. I used wrong values as coordinates.
