### ISSUE TITLE
Missing state 'charged'

### ISSUE THREAD

**Issue by JoramHhub** [humbertogontijo/homeassistant-roborock#15]
I think there is a state_code missing. 

HA displays the state as 'charging' while the roborock displays a 'charged' state.
Looking at the code (I'm a novice) I've found the state_codes and is doesn't have a code for 'charged'. I did a quick google search but couldn't find Roborock's status codes. If you can direct me to some documentation, I'd happily create a PR.

**Comment by humbertogontijo** [comment]
The states used are the same as the python-miio repository

**Comment by JoramHhub** [comment]
Thanks! I looked around and didn’t find anything about a ‘charged’. Now im wondering if its a totally different issue, will report a new issue explaining the problem.
