### ISSUE TITLE
Use menu instead of radio buttons

### ISSUE THREAD

**Issue by mvdwetering** [humbertogontijo/homeassistant-roborock#155]
I think it would be nice to use a menu instead of the radio buttons for selecting the platform to configure.
Just a suggestion, not a bug or something, more as an FYI

Menu looks something like this:
![image](https://user-images.githubusercontent.com/732514/213699293-fda69653-fd65-4c5b-b2bb-b912a7cf2925.png)

Clicking on an option will take you to the next step. 
Developer documentation for menus https://developers.home-assistant.io/docs/data_entry_flow_index/#show-menu

as another FYI you can set `last_step=False` to the call to show a form and you will get a "Next" button instead of "Submit"

**Comment by humbertogontijo** [comment]
Done in v0.0.28. Thanks for the tip
