### ISSUE TITLE
"Invalid calibration, please check your configuration"

### ISSUE THREAD

**Issue by amathews84** [humbertogontijo/homeassistant-roborock#166]
Every day or every other day I get the following error:

![Screenshot_20230127_140940_Home Assistant.jpg](https://user-images.githubusercontent.com/33185757/215196519-a3683392-a9ca-4a65-a0a1-74e15768a51c.jpg)

I'm unable to run any cleanings while I see this error.  Most of the time I can fix it by going to the devices and services page, clicking Roborock configuration and changing the map rotation to 90 degrees:

![Screenshot_20230127_141019_Home Assistant.jpg](https://user-images.githubusercontent.com/33185757/215197318-c14cea14-452a-4436-9c32-af9b6d4128f7.jpg)

After getting rid of the error I'll go back and change the map rotation back to 0 so that I can view the map in the proper orientation.  The error appears again within a day or two. Any idea why this might be happening?

**Comment by matt1131** [comment]
I'm getting the same thing on 0.0.27

**Comment by humbertogontijo** [comment]
This integration uses a mqtt client to communicate with the vacuum. But for whatever reason this client stop listening to new incoming msgs even when it is still connected. I've added some code to avoid this issue in latest version. Is it still happening?
