### ISSUE TITLE
Roborock App - Misleading

### ISSUE THREAD

**Issue by christian1986** [humbertogontijo/homeassistant-roborock#171]
From what I can tell, and from my testing this integration don't use the Roborock App credentials. It uses the Xiaomi Home credentials. The difference is that the Xiaomi Home(Mi Home) app does not support remote viewing.

Very glad if I'm wrong!

Edit:
After removing my Xiaomi Home account I get the following
"Could not login to Xiaomi Miio Cloud, check the credentials."

The Roborock App still works.

Edit2:
When I add the integration I get the following message:
"Support for Roborock devices is provided by Xiaomi Miio. Do you want to continue?"

Edit3:
It looks like a bug. Downloaded 0.24 and I where able to sign in.

**Comment by jappish84** [comment]
Seems to me you are over complicating things. If you've previously set up you vac with Mi home-app, download the roborock app -> go through the steps of setting up the robot with the official roborock app (reconnect to wifi). When everything is working in the roborock app, go ahead and install this custom integration and follow the instructions and you'll be good to go
