### ISSUE TITLE
Fan speed not translated

### ISSUE THREAD

**Issue by Menelao147** [humbertogontijo/homeassistant-roborock#180]
Hi, I don't know if it's a problem with my installation or if it's the same for everyone.
Entries in the fan speed combo box are not translated.
Is it possible to translate these elements too?

![image](https://user-images.githubusercontent.com/59983324/219322499-a6fb4d55-d2fa-4372-ac76-f59176dfbfbc.png)

**Comment by humbertogontijo** [comment]
Unfortunately it's not supported by home assistant yet. Only climate attributes are supported right now https://developers.home-assistant.io/docs/internationalization/core/#entity-state-attributes
