### ISSUE TITLE
Bad configuration?

### ISSUE THREAD

**Issue by Doser86** [humbertogontijo/homeassistant-roborock#181]

**Comment by humbertogontijo** [comment]
I'll investigate it. 
But you just shared the credentials to your Roborock account. Change your password as soon as possible so this credentials get invalidated

**Comment by humbertogontijo** [comment]
This looks like an issue with home assistant. Could you update yours?

**Comment by Doser86** [comment]
I have updated home assistant before I got this log

**Comment by humbertogontijo** [comment]
Should be fixed in v0.1.1

**Comment by Doser86** [comment]
Fixed now. You can close the case 👍

**Comment by Doser86** [comment]
Is there a way to collapse this card? Or flip it?
