### ISSUE TITLE
Possibility to hide ignored obstacles

### ISSUE THREAD

**Issue by Menelao147** [humbertogontijo/homeassistant-roborock#185]
Hi,
in the map extracted i sse a lot of blue dots that should be all the ignored obstacles.
Is there a way to hide them?

![image](https://user-images.githubusercontent.com/59983324/219623241-8eb06869-bec3-41a3-8a1d-003cd8a83f8d.png)

**Comment by Timminater** [comment]
I would like to see this option as well.

**Comment by Lash-L** [comment]
This will be included in the next major release - closing for now.
