### ISSUE TITLE
Integration fails to start: AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by dk1fiwa** [humbertogontijo/homeassistant-roborock#189]
The Integration fails to start. I'm running the latest version 0.1.1 . I do not know if this issue is particular related to this version or a prior version, because I did the last two updates without using the integration. I've tried to restart HA several times without any luck getting the integration run.

The protocol shows this error:

Error setting up entry Roborock for roborock

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 62, in async_setup_entry
    include_shared = vacuum_options.get(CONF_INCLUDE_SHARED) if vacuum_options else False
AttributeError: 'bool' object has no attribute 'get'

**Comment by humbertogontijo** [comment]
Can you remove the integration and login again?

**Comment by Lash-L** [comment]
@dk1fiwa are you still having this issue?
