### ISSUE TITLE
Multiple map entities/multi map support?

### ISSUE THREAD

**Issue by AKruimink** [humbertogontijo/homeassistant-roborock#190]
Looking at the entities exposed by this is see we have a camera.roborock_s7_map but what about those with multiple maps, is there any way to expose more than 1 for the xiaomi vacuum map card to consume, as i sometimes manually put the vacuum upstairs, for which it has a separate map.

**Comment by humbertogontijo** [comment]
Check out the service roborock.camera_load_multi_map

**Comment by AKruimink** [comment]
Any chance you could elebrotae on this? Rather new to home assistant in general, and doing a search for services in HA only resulted in info about scripts and service calls, is this what your taling about?

**Comment by Xyaren** [comment]
https://github.com/humbertogontijo/homeassistant-roborock/discussions/151
