### ISSUE TITLE
Make SCAN_INTERVAL configurable

### ISSUE THREAD

**Issue by benedikt-bartscher** [humbertogontijo/homeassistant-roborock#193]
there are 2 scan intervals hardcoded, one in camera.py and one in __init__.py

**Comment by benedikt-bartscher** [comment]
I already thought that it was intended, but we could set sensible defaults and warn about bans. Do you have any information about rate-limits/bans of the API?
For my specific use-case it would be awesome to adjust the interval at runtime (for example with a custom service). I need to open and close some doors via automations and my goal is to adjust the interval to for example 3 seconds for a short period of time. This would also allow to set the interval to a vey long time at night to reduce api calls/load.

**Comment by benedikt-bartscher** [comment]
If the API has endpoints to retrive night times we could also auto-adjust the intervals to a higher value at night. Or just retrive the night-times as attributes to the roborock vacuum entity and let users create their own automations for this.

**Comment by benedikt-bartscher** [comment]
Another way to accomplish this a little easier is to add a custom HA service like roborock.fetch and set reasonable low values for SCAN_INTERVAL. If users need faster updates or updates on a specific time, they can just call roborock.fetch to trigger a manual update.

**Comment by mvdwetering** [comment]
As far as I know Home Assistant does not allow for configurable scan intervals anymore (but in a custom component of course you can still do it). 

The intended way is to disable "Enable polling for updates" in the "System options" of the integration.
![image](https://user-images.githubusercontent.com/732514/226206760-d96e0b34-e188-49ad-99ee-1b9a14e3587a.png)

And then create an automation that periodically calls `homeassistant.update_entity` service with the interval you want.
Example of a service call.

```yaml
service: homeassistant.update_entity
data: {}
target:
  entity_id: sensor.random_joke
```

**Comment by benedikt-bartscher** [comment]
Thank you very much, i didn't knew that manual polling is already implemented in HA itself.
