### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by hellow554** [humbertogontijo/homeassistant-roborock#195]
Log is:

```
Logger: frontend.js.latest.202303010
Source: components/system_log/__init__.py:254
First occurred: 11:23:11 (5 occurrences)
Last logged: 11:26:54

:0:0 ResizeObserver loop completed with undelivered notifications.
```

I'm not sure if this is an actual error or just a warning message from hass, but I noticed it during me trying to get this integration working

**Comment by Lash-L** [comment]
I don't think this is a Roborock issue. 

Stems from the system log component. While I suppose it is possible that it is caused by Roborock, it is more likely something else going on. Are you still having this issue?
