### ISSUE TITLE
What would be needed to vacuum a named room?

### ISSUE THREAD

**Issue by grahamsz** [humbertogontijo/homeassistant-roborock#20]
I'd love to be able to vacuum the kitchen using a button press from my dashboard. Do you have an idea of how I'd start to integrate that (or what i'd need to update in this codebase?)

thanks,
Graham

**Comment by kristofferR** [comment]
Install Lovelace Vacuum Map card using HACS, add the card to a dashboard and edit it like this:
 
<img width="1053" alt="Skjermbilde 2022-12-14 kl  17 11 38" src="https://user-images.githubusercontent.com/481270/207648673-9418b31e-dfd4-45be-8bf4-8fce697dabfe.png">

Press generate rooms and generate static config. Click the blue icon next to "Zone cleanup" on the card, and select Rooms. Optionally click into "Show code editor" and edit the room names to what you want. Note the ID of the room you want, and do this:
<img width="925" alt="Skjermbilde 2022-12-14 kl  17 19 46" src="https://user-images.githubusercontent.com/481270/207650514-f6dc8354-73aa-493a-b475-303c66042fb3.png">
