### ISSUE TITLE
When used in an automation roborock.vacuum_goto doesn't work 

### ISSUE THREAD

**Issue by WilliamHusum** [humbertogontijo/homeassistant-roborock#200]
When I try to use the roborock.vacuum_goto in an automation, I get an error, saying that the xiaomi_miio.vacuum_goto doesn't exist.

`The automation "aaaa Delete" (automation.aaaa_delete) has an action that calls an unknown service: xiaomi_miio.vacuum_goto.`

The service works fine, when I call it directly from the Developer Tools tab, but not in automations or scripts. 

I'm not sure where the problem lies, but thought I would try here. 

- William

**Comment by humbertogontijo** [comment]
xiaomi_miio.vacuum_goto is a service provided by the xiaomi integration. For this one please use roborock.vacuum_goto
