### ISSUE TITLE
Change map in xiaomi vacuum map card not working

### ISSUE THREAD

**Issue by zoesn89** [humbertogontijo/homeassistant-roborock#201]
Hey guys,

I'm using the roborock integration since 2 days and I'm getting an error every time I try to change the map in the "xiaomi vacuum map card". This is the error text: roborock/camera_load_ multi_map. required key not provided @ data['map_flag]. But I'm definitely passing a value for the map flag to the command "roborock.camera_load_multi_map". Here is my code for the card:

type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.rocky_map
calibration_source:
  camera: true
entity: vacuum.rocky
vacuum_platform: default
two_finger_pan: true
title: ''
preset_name: Erdgeschoss
icons:
  - icon: mdi:play
    conditions:
      - entity: vacuum.rocky
        value_not: cleaning
      - entity: vacuum.rocky
        value_not: error
      - entity: vacuum.rocky
        value_not: returning
    tooltip: Start
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.rocky

...

  - icon: mdi:home-floor-0
    tooltip: Erdgeschoss
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      data:
        map_flag: 0
      target:
        entity_id: camera.rocky_map
  - icon: mdi:home-floor-1
    tooltip: Obergeschoss
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      data:
        map_flag: 1
      target:
        entity_id: camera.rocky_map
  - icon: mdi:home-floor-2
    tooltip: Kellergeschoss
    tap_action:
      action: call-service
      service: roborock.camera_load_multi_map
      data:
        map_flag: 2
      target:
        entity_id: camera.rocky_map
map_modes:
  - name: Zone reinigen
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: EXTERNAL
    max_repeats: 3
    service_call_schema:
      service: roborock.vacuum_clean_zone
      service_data:
        zone: '[[selection]]'
        repeats: '[[repeats]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}

...

additional_presets:
  - preset_name: Obergeschoss
    entity: vacuum.rocky
    map_source:
      camera: camera.rocky_map
    calibration_source:
      camera: true
    activate_on_switch: true
    activate:
      service: roborock.camera_load_multi_map
      target:
        entity_id: camera.rocky_map
      data:
        map_flag: 1
...

  - preset_name: Kellergeschoss
    entity: vacuum.rocky
    map_source:
      camera: camera.rocky_map
    calibration_source:
      camera: true
    activate_on_switch: true
    activate:
      service: roborock.camera_load_multi_map
      target:
        entity_id: camera.rocky_map
      data:
        map_flag: 2
    map_modes:
      - name: Zone reinigen
        icon: mdi:select-drag
        run_immediately: false
        coordinates_rounding: true
        selection_type: MANUAL_RECTANGLE
        max_selections: 5
        repeats_type: EXTERNAL
        max_repeats: 3
        service_call_schema:
          service: roborock.vacuum_clean_zone
          service_data:
            zone: '[[selection]]'
            repeats: '[[repeats]]'
            entity_id: '[[entity_id]]'
        predefined_selections: []
        variables: {}
 ...

Does someone have a clue?

Thanks in advance ;)
Felix

**Comment by Xyaren** [comment]
Also this is not a humbertogontijo/homeassistant-roborock issue.
If at all this is a [PiotrMachowski/lovelace-xiaomi-vacuum-map-card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card) discussion.

**Comment by zoesn89** [comment]
Hey Xyaren,

thanks for your script! It's working perfectly ;) I initially thought it was an issue with the Xiaomi vacuum map card, but it worked fine with the Xiaomi Mi integration, so I figured it must be a problem with the roborock integration. 

Again, thank you! ;)
