### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by intucom** [humbertogontijo/homeassistant-roborock#220]
When I set it up in Home Assistant I get a: 
Error fetching roborock data: Timeout after 4 seconds waiting for response

What Did I do wrong?

**Comment by Lash-L** [comment]
Open hacs, then select the Roborock integration, hit the three dots in the top, then redownload and make sure you have version 0.1.2 selected and not main

**Comment by intucom** [comment]
I tried that now. Im afraid that didnt fix it

**Comment by Lash-L** [comment]
You restarted as well?

**Comment by intucom** [comment]
Of course

**Comment by intucom** [comment]
Do you have any other idea how to fix this?

Its a completely errorfree and up to date new HA Setup

Is there maybe something wrong with my Roborock account?

**Comment by intucom** [comment]
I'm getting there Lines in the Log:

2023-04-02 14:45:13.955 WARNING (MainThread) [homeassistant.config_entries] Config entry 'my.mail@adress.com' for roborock integration not ready yet: None; Retrying in background
2023-04-02 14:45:20.496 WARNING (MainThread) [roborock.api] Roborock mqtt client disconnected (rc: 7)
2023-04-02 14:45:24.496 ERROR (MainThread) [custom_components.roborock] Error fetching roborock data: Timeout after 4 seconds waiting for response

**Comment by devcomputer** [comment]
I get an infinite blue indicator on both auth methods. https://imgur.com/a/ebqrYBU

**Comment by Lash-L** [comment]
@intucom @devcomputer 

Odd. 

I just fully removed the integration from my side and reinstalled it on 0.1.2 and I didn't have any issues. 

@devcomputer Make sure you don't have any firewall settings that would be getting in the way for any reason communicating with Roborock's servers. Also obligatory make sure you have restarted home assistant. 

@intucom Do you have your robot on your roborock account/app? What region are you in? Potentially that is causing some issues?

**Comment by devcomputer** [comment]
The default Xiaomi Mii intergrations has no trouble talking to the server but lets me choose which server. I removed any Xiomi mi integrations. added your intergration 0.1.2 through hacs but I just see the animation on the Your app credentials screen after pressing submit.

**Comment by Lash-L** [comment]
@devcomputer Do you have a roborock account? Are you attempting to login with your Xiaomi Mii account or your roborock account?

**Comment by devcomputer** [comment]
:-(
xiaomi

**Comment by Lash-L** [comment]
Make a Roborock account and use those credentials and then let me know if you are still having issues.

We are authing directly with Roborock - not through Xiaomi

**Comment by devcomputer** [comment]
https://usaccount.roborock.com/login/reegister  does not have europe. so did a US account. no devices at rockrobo. 
how to migrate old vacuum from Mii to roborock?

anyways, login with email I receive a code but after entering code I am stuck again...same when I use username and password.

**Comment by Lash-L** [comment]
To migrate you should be able to remove it from the Mii app, then just add it in roborock app. If you go through the steps it should just work. 

If you do all that and you still can't log in @humbertogontijo may have a better idea.

**Comment by devcomputer** [comment]
roborock.com only support s5 and up.  :-1:

**Comment by kodek** [comment]
I just ran into this issue. My setup was working correctly until I messed with it [1].

Things I tried:

1. Redownloading 0.1.2
2. Restarting HA.
3. Removing and re-adding integration.
4. Authenticating via password AND email code (both auth methods succeed).


Things I have not tried just yet:
1. Removing _everything_ at the same time (custom component AND integration).


[1] I switched to the main branch, but I quickly switched back.

**Comment by humbertogontijo** [comment]
@kodek is your device reachable? Can you access it from Roborock app?

**Comment by kodek** [comment]
Thanks, that was it! I have two robots, and one of them was offline. Once I got the device back in the charger, the HA integration was able to initialize successfully.

I haven't looked at the code too closely, but what sort of information is available as the devices are initialized? A few suggestions to make troubleshooting a bit easier:

* If available, include the device's name (or an identifier) in the error messages.
* Convert the `rc` [error code](https://github.com/eclipse/paho.mqtt.python/blob/a4cb435ca2864d073ea3e0e18b0407e4bbe85b16/src/paho/mqtt/client.py#L156-L174) from an integer back to a string. Could [this function](https://github.com/eclipse/paho.mqtt.python/blob/a4cb435ca2864d073ea3e0e18b0407e4bbe85b16/src/paho/mqtt/client.py#L189) be used?
* If possible, it might be great to fail only on the devices that are unavailable.

**Comment by tension81** [comment]
@kodek @humbertogontijo Thanks! That solved my issue as well ... my second robot was offline too.
