### ISSUE TITLE
Logger: roborock.api Source: runner.py:179 First occurred: 03:43:47 (2 occurrences) Last logged: 09:44:25  Roborock mqtt client disconnected (rc: 16)

### ISSUE THREAD

**Issue by nikrays** [humbertogontijo/homeassistant-roborock#224]
Logger: roborock.api
Source: runner.py:179
First occurred: 03:43:47 (2 occurrences)
Last logged: 09:44:25

Roborock mqtt client disconnected (rc: 16)

**Comment by Lash-L** [comment]
Are you having other issues or just this log?

**Comment by nikrays** [comment]
> Are you having other issues or just this log?

Only this one

**Comment by Lash-L** [comment]
The mqtt client will just disconnect and reconnect sometimes. It's not a bug or anything you need to worry about unless if it is happening extremely frequently. Closing for now
