### ISSUE TITLE
Room cleaning isn´t possible

### ISSUE THREAD

**Issue by MikeDeltaHH** [humbertogontijo/homeassistant-roborock#237]
## Version of the custom_component

0.1.2

## What vacuum are you using?

Roborock S5 Max

## Describe the bug

I have successfully integrated this version and then the the Xiaomi Vacuum Map Card and was able to create a Room Config with 4 rooms via "generate room config". The zone cleaning also works, but when I want to clean a room nothing happens and in the log are error messages.

The Config:

type: custom:xiaomi-vacuum-map-card
map_source:
  camera: camera.roborock_s5_max_map
calibration_source:
  camera: true
entity: vacuum.roborock_s5_max
vacuum_platform: send_command
map_modes:
  - name: Zone cleanup
    icon: mdi:select-drag
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_RECTANGLE
    max_selections: 5
    repeats_type: INTERNAL
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_zoned_clean
        params: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Pin & Go
    icon: mdi:map-marker-plus
    run_immediately: false
    coordinates_rounding: true
    selection_type: MANUAL_POINT
    max_selections: 999
    repeats_type: NONE
    max_repeats: 1
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_goto_target
        params: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections: []
    variables: {}
  - name: Rooms
    icon: mdi:floor-plan
    run_immediately: false
    coordinates_rounding: true
    selection_type: ROOM
    max_selections: 999
    repeats_type: REPEAT
    max_repeats: 3
    service_call_schema:
      service: vacuum.send_command
      service_data:
        command: app_segment_clean
        params: '[[selection]]'
        entity_id: '[[entity_id]]'
    predefined_selections:
      - id: '16'
        icon:
          name: mdi:broom
          x: 23900
          'y': 27900
        label:
          text: Küche
          x: 23900
          'y': 27900
          offset_y: 35
        outline:
          - - 21700
            - 25250
          - - 26100
            - 25250
          - - 26100
            - 30550
          - - 21700
            - 30550
      - id: '17'
        icon:
          name: mdi:broom
          x: 20775
          'y': 28850
        label:
          text: Flur
          x: 20775
          'y': 28850
          offset_y: 35
        outline:
          - - 19900
            - 28400
          - - 21650
            - 28400
          - - 21650
            - 29300
          - - 19900
            - 29300
      - id: '18'
        icon:
          name: mdi:broom
          x: 19100
          'y': 26825
        label:
          text: Schlafzimmer
          x: 19100
          'y': 26825
          offset_y: 35
        outline:
          - - 16550
            - 25250
          - - 21650
            - 25250
          - - 21650
            - 28400
          - - 16550
            - 28400
      - id: '19'
        icon:
          name: mdi:broom
          x: 18250
          'y': 29050
        label:
          text: Badezimmer
          x: 18250
          'y': 29050
          offset_y: 35
        outline:
          - - 16650
            - 28400
          - - 19850
            - 28400
          - - 19850
            - 29700
          - - 16650
            - 29700
    variables: {}

## log

Logger: homeassistant
Source: custom_components/roborock/device.py:92
Integration: Roborock ([documentation](https://github.com/humbertogontijo/homeassistant-roborock), [issues](https://github.com/humbertogontijo/homeassistant-roborock/issues))
First occurred: 10. April 2023 um 14:35:47 (4 occurrences)
Last logged: 10. April 2023 um 15:42:00

Error doing job: Task exception was never retrieved
roborock.exceptions.VacuumError: -10005: data for segment is not a number

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/roborock/vacuum.py", line 526, in async_send_command
    return await self.send(command, params)
  File "/config/custom_components/roborock/device.py", line 92, in send
    return await self.coordinator.api.send_command(self._device_id, command, params)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 402, in send_command
    raise CommandVacuumError(method, err) from err
roborock.exceptions.CommandVacuumError: app_segment_clean: -10005: data for segment is not a number

------

I'm quite a HA newbie, so sorry if I may have made a mistake here - am grateful for any help and find the integration really great!

**Comment by Lash-L** [comment]
How are you attempting to clean the room? Could you give a bit more information?

**Comment by humbertogontijo** [comment]
@MikeDeltaHH Remove the quotes for each room id in predefined_selections

**Comment by MikeDeltaHH** [comment]
@humbertogontijo  Thanks a lot for your help, it worked like a charme now! :)
