### ISSUE TITLE
no_device error

### ISSUE THREAD

**Issue by mvillarejo** [humbertogontijo/homeassistant-roborock#24]
Hello,

I was just trying to setup my Roborock S6 but I'm getting the following error:
<img width="381" alt="Screenshot 2022-12-15 at 13 12 04" src="https://user-images.githubusercontent.com/4228967/207856579-63d577bb-f29a-486a-84c3-bc1b9afdf542.png">
just wondering if S6 is not supported or there's something wrong with my account. 

Only debug message I'm receiving is:
2022-12-15 11:51:03.980 DEBUG (MainThread) [custom_components.roborock.config_flow] Starting a scan for Roborock devices

cheers

**Comment by humbertogontijo** [comment]
Is your devices registered in the mi app or Roborock app? If it is the Roborock app, do you know which country you are resgistered to?

**Comment by humbertogontijo** [comment]
Is your devices registered in the mi app or Roborock app? If it is the Roborock app, do you know which country you are resgistered to?

**Comment by mvillarejo** [comment]
Mi App not roborock

**Comment by kristofferR** [comment]
This extension is for Roborock. If you want to use Mi Home, use https://www.home-assistant.io/integrations/xiaomi_miio/

**Comment by mvillarejo** [comment]
oh! didn't know that. Registered with Roborock app and it's working good.

Thank you for the contribution
