### ISSUE TITLE
Warning in Log Status

### ISSUE THREAD

**Issue by Maxi2509** [humbertogontijo/homeassistant-roborock#240]
i got a lot of warning in my log - see below:

Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:491
Integration: Recorder ([documentation](https://www.home-assistant.io/integrations/recorder), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+recorder%22))
First occurred: 17:02:42 (22 occurrences)
Last logged: 17:03:08

State attributes for camera.top_jobs_map exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for camera.dachgeschoss_map exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for camera.1_stock_map exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for camera.nunn_map exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for camera.erdgeschoss_map exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

is there any possibility to limit this and/or shut it off?

Greetings Maxi

**Comment by Lash-L** [comment]
see https://github.com/humbertogontijo/homeassistant-roborock/issues/196#issuecomment-1475354096

This will be fixed in the next major release, but until then, this is a solution you can do.
