### ISSUE TITLE
Possible to zoom/crop the map?

### ISSUE THREAD

**Issue by dhc25** [humbertogontijo/homeassistant-roborock#258]
Is it possible to zoom in, or crop, the map image?
Using this in a picture-entity card, it has a lot of white space around the map.
Thanks in advance

**Comment by humbertogontijo** [comment]
Have you tried map scale within integration options?

**Comment by dhc25** [comment]
Got it - thanks - I hadn't seen those options before. 
Nicely cropped and zoomed now. Thanks for your help.
