### ISSUE TITLE
Integration not availablein HACS

### ISSUE THREAD

**Issue by Crimby88** [humbertogontijo/homeassistant-roborock#263]
The complete integration is missing in HACS. Can't find anything on Roborock. 
Please fix or provide steps to manually install the integration.
Thank you.

**Comment by Lash-L** [comment]
In hacs in your home assistant instance, you need to hit the three dots in the top right, then add repository, then put the link for this integration there.

Then you can download it from hacs

**Comment by Lash-L** [comment]
Was that clear @Crimby88 - were you able to figure it out?

**Comment by croziors** [comment]
what is repot url ?

**Comment by TheDelta** [comment]
Just ran into this as well, I though it's available in the default

Simply go to HACS page > Integration > Top right the 3 dots menu > Custom reposetories > Add as url `https://github.com/humbertogontijo/homeassistant-roborock` and category is Integration.

Thats it.

Might make sense to add install instructions to the readme or get into the default repository list. <3

**Comment by Lash-L** [comment]
> Might make sense to add install instructions to the readme
![image](https://github.com/humbertogontijo/homeassistant-roborock/assets/20257911/6aff72ff-763a-4ce3-ba6d-96572e01e831)

It is in the readme

> or get into the default repository list. <3

We can't. HACS doesn't allow a repo with the same name as a core integration in the default list

**Comment by croziors** [comment]
Work. Now thx
