### ISSUE TITLE
Integration Rename Makes all Sensors Unavailable

### ISSUE THREAD

**Issue by drizztguen77** [humbertogontijo/homeassistant-roborock#264]
It  seems to be using the integration name as the connection or something. It is using the email address for the integration name. When you rename it all the sensors suddenly become Unavailable. Renaming it back does not fix it. You actually have to completely remove the integration and re-add it to get the sensors back.

Roborock S7 Ultra Max

![Roborock S7 MaxV Email Integration Name](https://user-images.githubusercontent.com/1878537/235361850-dfebf52a-f781-4d2c-8f4a-00f4ad047d90.png)
![Roborock S7 MaxV Renamed Integration](https://user-images.githubusercontent.com/1878537/235361869-2377067d-2d14-4eee-98e7-4e5f364e9d15.png)
![Roborock S7 MaxV Unavailable Sensors](https://user-images.githubusercontent.com/1878537/235361873-a832b23e-7592-4b75-a2c1-4f7cf5d3d330.png)

**Comment by Lash-L** [comment]
I can't recreate this. I changed the name for mine by using "rename" and it did not mess up. 

It shouldn't be related to anything - as the unique id is created in the background and that just shows it. Renaming it shouldn't cause any HA issues

**Comment by drizztguen77** [comment]
So any ideas on how to get around it? When it sees the vacuum it asks me for the email address or phone number. I give it my wifes email address and it sends her a code. I provide the code and it connects and all the sensors are working as normal. But as soon as I rename the integration everything goes to Unavailable. Does it matter which phone app we are using? We are using the Roborock app. I'm open to try any ideas you have as to what I can do to get it fixed. Maybe I'm adding it incorrectly or something???

**Comment by drizztguen77** [comment]
It looks like I'm on version 0.1.2, the one in HACS. If there is anything I can do to help debug it I'm happy to do that. I'm just not familiar with how everything works under the hood yet.

**Comment by Lash-L** [comment]
Okay - just took another look and downgraded myself to 1.2

The issues happens there, but not on the main branch.

If you want you can go to HACS, select Roborock, settings, redownload, then select main.

It is a beta branch though, so you may run into some unexpected issues, but it seems like we have fixed this issue without even knowing it was an issue.

If you don't want to update to main, you can wait until we officially release the next version

**Comment by drizztguen77** [comment]
Ok yep I just went to the main version and that worked. So it's fixed on the main branch. I'll just use that until it's released. I like the new features of being able to turn off the mopping.

**Comment by Lash-L** [comment]
Sounds good! Just keep in mind it is our main branch and is not always expected to be stable. We have known bugs/ currently in progress code on it. That being said - should be good for most cases!
