### ISSUE TITLE
Unknown error while setting up integration.

### ISSUE THREAD

**Issue by deam0n** [humbertogontijo/homeassistant-roborock#265]
## Version of the custom_component

0.1.2

## What vacuum are you using?
Xiaomi Roborock S5

## Describe the bug

When trying to add the vacuum, I'm prompted with 2 auth methods. I choose Token, I enter my email, I get the code via email, but when I enter the code in Home Assistant, I get an error:

Unknown error occurred

(Same happens with Password authentication)

## Debug log

Not possible as I cannot add the integration. There are no errors related in HA Core log.

**Comment by Lash-L** [comment]
You can only add Roborock vacuums that are synced with your roborock account. I believe the s5 can't be added to the Roborock app - only the mi home app

**Comment by deam0n** [comment]
indeed!!

thanks
