### ISSUE TITLE
Local API - vacuum frequently goes offline if it doesn't have Internet connectivity

### ISSUE THREAD

**Issue by jaydeethree** [humbertogontijo/homeassistant-roborock#273]
## Version of the custom_component

main branch at commit 269462d

## What vacuum are you using?

Roborock S7

## Describe the bug

I'm using this integration with `Beta: use local integration` enabled. This works well, however I noticed that if I block all traffic from my Roborock vacuum to the internet by setting firewall rules on my router then the vacuum frequently goes offline/becomes unavailable. See attached image - the large periods of time that show "Docked" are when I was allowing traffic from the vacuum to the internet. The other times (where the vacuum frequently becomes unavailable) were during times that I was blocking traffic between the vacuum and the internet, but still allowing traffic from the vacuum to my LAN.

![Screenshot 2023-05-02 085834](https://user-images.githubusercontent.com/34945248/235725915-48388cc4-bde2-4950-a94a-63021837739e.png)

## Debug log

```text

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 192, in _async_response
    raise RoborockTimeout(f"Timeout after {QUEUE_TIMEOUT} seconds waiting for response") from None
roborock.exceptions.RoborockTimeout: Timeout after 4 seconds waiting for response

Roborock client disconnected
[Errno 104] Connection reset by peer
Timeout after 4 seconds waiting for response
```

**Comment by benedikt-bartscher** [comment]
I have the same issue on main brach. @Lash-L block it on the whole network or just for the roborock or for home assistant?

**Comment by Lash-L** [comment]
Yes - we have been unable to reverse engineer the map for local control.

I'm not sure where/how to block it I have not attempted it yet. @humbertogontijo would know

**Comment by jaydeethree** [comment]
@Lash-L thanks for the quick response! I spent a bit of time testing this and running TCPDump - here are my findings so far:

* If you block mqtt-us-2.roborock.com (I set it to return NXDOMAIN from my DNS server). then the Roborock will attempt to bypass your local DNS and do the lookup through 8.8.8.8:53 (Google Public DNS).
* Returning NXDOMAIN for mqtt-us-2.roborock.com does not fix the frequent disconnects from Home Assistant - they continue to happen.
* Allowing the domain to be resolved but blocking its traffic (which goes to AWS) also does not fix the frequent disconnects from Home Assistant - they continue to happen.
* At about the same time that each disconnect happens, the Roborock sends out a new DHCPDISCOVER. So it seems like when the Roborock can't connect to its AWS instance it cycles its network interface which is almost certainly the cause of the disconnects from Home Assistant. Looking at my Wifi AP logs it appears the Roborock is disconnecting from the Wifi network and reconnecting each time this happens.

I'm still trying to figure out if there's a way around this, but it seems likely that the Roborock firmware just cycles the network interface if it can't connect to Roborock's AWS instance. In that case it may be impossible for us to do anything about this, but I'm still trying various things to see what I can figure out.

**Comment by jaydeethree** [comment]
Allowing the vacuum to send traffic to the Internet on TCP port 8883 (MQTTS) fixes the issues with it becoming unavailable in Home Assistant. That does mean that it's reporting data back to Roborock, but this at least limits the vacuum to MQTT data so I probably don't have to worry about it becoming part of a botnet or connecting to random other stuff. I would assume that firmware updates are served over HTTPS and that this will prevent the vacuum from updating, but I have no way of testing that. I also noticed that after making the initial MQTTS connection the vacuum will also try to talk to awsusor0.fds.api.xiaomi.com and api-us.roborock.com - I need to experiment with returning NXDOMAIN for those to see if it breaks anything.

At this point I suspect the only way to get 100% local control is to install Valetudo.

**Comment by humbertogontijo** [comment]
I was able to reverse engineer the map request locally. The app still requests locally.
The problem is that the cleaner does not return the data.

Since the app still prompts for this, I'm leading myself to believe that the map was previously a local resource, but for whatever reason it have become an online resource.
Like when them introduced the feature for taking pictures of objects

**Comment by humbertogontijo** [comment]
The integration requesting the map for mqtt could be the issue for the entities becoming unavailable.
@jaydeethree do you have the last command sent when it times out and become unavailable?

**Comment by Lash-L** [comment]
> I was able to reverse engineer the map request locally. The app still requests locally.

Ah yes that's what I meant when I said yet to reverse engineer it.

I mean the xiaomi integration is able to do it locally right? I would assume that means it is at least possible for it to be stored locally. Butperhaps once the vacuum has been configured to communicate with Roborock software it just works different so I'm not sure. 

I would have to think there is still some means of making it work, but I'm not sure.

**Comment by jaydeethree** [comment]
> @jaydeethree do you have the last command sent when it times out and become unavailable?

Looking at my logs I see that the integration is requesting map data every 5 seconds and uses a 4-second timeout for the request, so at almost any time there's a request that's in-flight for map data. So yes, there are map data requests right before it becomes unavailable, but there are so many map data requests that it seems impossible for me to know if that's actually related.

I'm going to try modifying [the get_map() call](https://github.com/humbertogontijo/homeassistant-roborock/blob/931d7c8f3c0823aa3c57676b2b222cc2e3fb4695/custom_components/roborock/camera.py#L267) to just return None and also modifying [the coordinator](https://github.com/humbertogontijo/homeassistant-roborock/blob/931d7c8f3c0823aa3c57676b2b222cc2e3fb4695/custom_components/roborock/coordinator.py#L32) to never instantiate RoborockMqttClient and I'll see if that makes any difference. Thanks for your help!

**Comment by jaydeethree** [comment]
Some more observations from my testing:

* Removing map-related calls from this integration does not change anything - the vacuum still frequently becomes unavailable if its Internet access is blocked. TCPDump shows that the vacuum continues trying to connect over MQTTS to Roborock's servers even if nothing is requesting map data.
* Dropping the vacuum's packets to the Internet vs. rejecting the packets (with a TCP RST) makes no difference - both cause the vacuum to become unavailable.

As I mentioned before it seems like the vacuum tries to connect to Roborock over MQTTS several times, and if those connections fail then the vacuum cycles its network interface (disconnects from the WiFi SSID, reconnects to it, and goes through the DHCP process). If this was using insecure MQTT then I could just have my router silently redirect the traffic to my local MQTT broker, but since it's MQTTS that isn't going to work. For now I'm satisfied with only allowing the vacuum to send MQTTS traffic (TCP port 8883) and blocking all other traffic between the vacuum and the Internet.

**Comment by humbertogontijo** [comment]
@Lash-L even the app do not present the map if mqtt is broked

@jaydeethree After setting get_map to return None, have you checked the last command before timeout? Also, are you seeing logs for new connections after it times out?

**Comment by jaydeethree** [comment]
>@jaydeethree After setting get_map to return None, have you checked the last command before timeout? Also, are you seeing logs for new connections after it times out?

The last command doesn't seem to matter - I've done some more testing and confirmed that the vacuum dropping off of the network has nothing to do with this integration. I disabled this integration in Home Assistant, started running TCPDump, and then blocked all traffic between the vacuum and the Internet. With TCPDump I can confirm that Home Assistant is not trying to talk to the vacuum, but despite that the vacuum still cycles its network interface every 30-60 seconds - it disconnects from my WiFi SSID, reconnects to it, and then starts the DHCP process. So that seems to confirm that this is behavior that's part of Roborock's firmware and that the trigger seems to be a failure to connect to mqtt-us-2.roborock.com. Based on that I don't think there's anything that can be done in this integration to fix this.

I've also confirmed that returning NXDOMAIN for the other two Roborock domains (awsusor0.fds.api.xiaomi.com and api-us.roborock.com) does not cause any problems. The *only* traffic I'm allowing from the vacuum to the internet is to mqtt-us-2.roborock.com on TCP port 8883 and everything seems to work fine with that. At some point I may take apart my vacuum so I can install [Valetudo](https://github.com/Hypfer/Valetudo) on it, which would make it run 100% locally.

Thanks for building this integration and for all of your helpful responses in this issue!

**Comment by tacticallinux** [comment]
@jaydeethree Don't know if you will see this in a closed issue, I have a similar problem with local control of a Q5+ but I don't see the vacuum interface going up and down nor a DHCP renew.

If I block the vacuum from the Internet it will shortly disappear from HA although I can still see it on WiFi and I can still ping it just fine. It was continuing to try to hit mqtt-us-2.roborock.com and AWS but never showed up again in HA. 

I did a full reboot of HA and oddly it showed back up in HA and I could control it just fine from HA. When I reboot HA the vacuum and all my IoT doesn't have internet access by default, I have to specifically open up the Internet for the VLAN the vacuum and my other IoT sits on. 

So at the moment the Internet is blocked, the vacuum still shows docket/stats/etc in HA but after a few minutes I can no longer control it.

Interested in discussing this further somewhere, or is here appropriate? I bought this Q5+ a few days ago specifically because HA reports local polling on it's Roborock integration page and several redditors report the ability to control local only. As you have found out this apparently is incorrect.

**Comment by Lash-L** [comment]
@tacticallinux i think this is still worth discussing, but I would say it should be done in a discussion post and not this issue

**Comment by jaydeethree** [comment]
>I bought this Q5+ a few days ago specifically because HA reports local polling on it's Roborock integration page and several redditors report the ability to control local only. As you have found out this apparently is incorrect.

I highly suspect this varies by device model and firmware version, since the behavior seems to be baked into Roborock's firmware. I'll post some additional info in [the discussion you created](https://github.com/humbertogontijo/homeassistant-roborock/discussions/320) and we can continue the conversation there.
