### ISSUE TITLE
Failed to set up on latest main

### ISSUE THREAD

**Issue by tomassj9** [humbertogontijo/homeassistant-roborock#283]
## Version of the custom_component

Main 31e1012

## What vacuum are you using?
Roborock Q7 Max Plus

## Describe the bug

Latest main fails to set up the device. Already redownloaded, and cleaned all integration related stuff.

## Debug log

```
DEBUG (MainThread) [custom_components.roborock] Got home data HomeData(*** all the normal stuff ***)

ERROR (MainThread) [homeassistant.config_entries] Error setting up entry *** mail *** for roborock: Device 60xvpEOUpVElH2jwST9GNC not found among {}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 101, in async_setup_entry
    devices_network = await get_local_devices_info(device_info)
  File "/config/custom_components/roborock/__init__.py", line 144, in get_local_devices_info
    raise ConfigEntryError(f"Device {device_info.device.duid} not found among {devices_network}")
homeassistant.exceptions.ConfigEntryError: Device 60xvpEOUpVElH2jwST9GNC not found among {}
```

**Comment by humbertogontijo** [comment]
Latest main is now not using mqtt to retrieve device ip. It's listening for broadcasts on port 58866. 
Is your device online? 
After updating to latest main the device needs to be available once, so it can cache it's ip

**Comment by tomassj9** [comment]
Okay, I didn't know. Well, I have the device in other VLAN / Firewall Rules, so it can be the problem. The device is online. I'm going to try using the given info!

**Comment by humbertogontijo** [comment]
Try allowing HA instance to listen for roborock device broadcasts on port 58866 and see if it works

**Comment by shred86** [comment]
Does having the Roborock on a separate VLAN require IP masquerading like it [does with python-miio](https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets)?

**Comment by humbertogontijo** [comment]
The vacuum broadcast constantly when it's using "Roborock protocol". So there is no need to send a broadcast to receive another one back. But the HA instance needs to be able to receive that broadcast from the vacuum

**Comment by humbertogontijo** [comment]
I'm thinking about adding integration options to set the vacuum ip manually. Similar to what localtuya does

**Comment by tomassj9** [comment]
Well, this would solve my problem, because direct IP connection works. With localtuya I'm using the same setup, but no auto-discovery is available, I need to input the IP for every device on the separate VLAN. For me, it's not a problem. I continue to be available for testing, should you require it.

**Comment by tomassj9** [comment]
Creating a VLAN interface on the host machine for listening to broadcasts (Interface + FW Rules) and using the host networking in Docker solves the issue, and it can connect to the device. No privileged mode needed on Docker. I prefer to separate all IoT into a separate VLAN and have granular control over the network, but it has downsides as this (can't rely on broadcast packets on other vlans without forwarding them or so). I've tried to masquerade and forward the packets without success, using my main router (Mikrotik)

Currently, facing other issue (#287).
It would be a great feature to have the old method as a backup in these cases, or directly put the IP of the device. I don't know which way is the best.

 Anyway, thanks Humberto & Luke for this hard work! The progress this project is making in such small-time is awesome. <3

**Comment by humbertogontijo** [comment]
It should be caching network information again in latest main

**Comment by mang1985** [comment]
I'm having the same problem with my S7 MaxV Ultra.

**Comment by mang1985** [comment]
> I'm thinking about adding integration options to set the vacuum ip manually. Similar to what localtuya does

My  vacuum is S7 MaxV Ultra.I use the Home Assistant Operating System installed in a VMware Workstation virtual machine, with the network adapter set to bridge mode. With the latest main version, I am still unable to set it up successfully. If this feature can be added, it should be able to solve my problem. Thank you.
