### ISSUE TITLE
[QUESTION] Is this related to the now official roborock integration?

### ISSUE THREAD

**Issue by jagjordi** [humbertogontijo/homeassistant-roborock#284]
With home assistant release 2023.35 a Roborock integration is officially supported: https://www.home-assistant.io/blog/2023/05/03/release-20235/#new-integrations

Is this related to this custom component? Should we migrate to the official integration?

**Comment by carlreid** [comment]
The [related PR](https://github.com/home-assistant/core/pull/89456#issue-1617717505) states:
> This is a conversion of the popular hacs integration: https://github.com/humbertogontijo/homeassistant-roborock.

and

> This integration uses the following pypi package: https://github.com/humbertogontijo/python-roborock

So it looks like it's built on the work here. Think I'll keep using this HACS version since it's closer to the original source and I'd imagine would get any fixes/improvements sooner

**Comment by Lash-L** [comment]
Yep - if you already have the HACS version I'd recommend sticking with the hacs version at least for a few updates.

Core is theoretically more stable as there are more eyes on it, and theres a beta test before it gets officially released, so you should have less bugs.

But the hacs version is A) super ahead right now and B) We can add new features and fixes without delay.

In the future it will just depend if you care more about stability or functionality. For right now though - I'd stick with HACS
