### ISSUE TITLE
auto_dust_collection?

### ISSUE THREAD

**Issue by rethamazur** [humbertogontijo/homeassistant-roborock#286]
Hello and thanks for this awesome integration!
My dilemma: I have a small home, less then 60 square meters to clean. Enabling auto dustbin collection from the roborock app makes the base (S7 maxv ultra) empty the dustbin after every room/zone cleaning cycle.
I thought it was a waste of energy (and a lot of noise), so I decided to manually trigger the dustbin emptying every 2-3 days.
Now I realized I could create an automation that triggers after a given amount of cleaned square meters, but I don't know how to turn on the auto_dust_collection attribute, or if it is even possible

**Comment by Lash-L** [comment]
You should be able to use the services tool in HA

Vacuum: Send command -> Select your roborock as the entity

then app_start_collect_dust as the command.

I don't think we have the prefix for it reverse engineered for local, but I'll try to add that in the future.

If you're not connected local(i.e. version 1.2 or older mains), it should work.

**Comment by humbertogontijo** [comment]
I'll give this a try https://github.com/humbertogontijo/python-roborock/commit/3124d7ea6277ec08d8e592448b2a4f8cb60fb7db
My device responded to this prefix

**Comment by rethamazur** [comment]
> You should be able to use the services tool in HA
> 
> Vacuum: Send command -> Select your roborock as the entity
> 
> then app_start_collect_dust as the command.
> 
> I don't think we have the prefix for it reverse engineered for local, but I'll try to add that in the future.
> 
> If you're not connected local(i.e. version 1.2 or older mains), it should work.

that worked, thanks a lot!
