### ISSUE TITLE
map exceed maximum size 

### ISSUE THREAD

**Issue by Birdman86** [humbertogontijo/homeassistant-roborock#289]
## Version of the custom_component
0.1.2

## What vacuum are you using?
Roborock S7+

## Describe the bug

Getting this warning/error constantly regarding the map sensor.

## Debug log

```text

Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:585
Integration: Recorder ([documentation](https://www.home-assistant.io/integrations/recorder), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+recorder%22))
First occurred: 12:29:56 (2 occurrences)
Last logged: 12:34:56

State attributes for camera.roborock_s7_map exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

```

**Comment by humbertogontijo** [comment]
This is already fixed in main

**Comment by Birdman86** [comment]
So how do I get this fix?

**Comment by humbertogontijo** [comment]
Download main from HACs instead of 0.1.2. You can do that by redownloading the integration and selecting main

**Comment by Birdman86** [comment]
Oh, OK, didn't know there was a "main" version.
Tried that now, but this one is even worse as it won't even connect to the unit...



Error setting up entry X  for roborock: Device X not found among {}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 92, in async_setup_entry
    devices_network = await get_local_devices_info(_device)
  File "/config/custom_components/roborock/__init__.py", line 141, in get_local_devices_info
    raise ConfigEntryError(f"Device {device.duid} not found among {devices_network}")
homeassistant.exceptions.ConfigEntryError: Device X not found among {}

**Comment by humbertogontijo** [comment]
Main is using local integration now. Is your device reachable from your HA instance?
This integration tries to listen for broadcasts on port 58866

**Comment by Birdman86** [comment]
It is weird, the local integration works fine and this custom one also works fine, minus this error.
But now with the main version, nothing seems to work...
