### ISSUE TITLE
roborock s6 maxv have no all sensors

### ISSUE THREAD

**Issue by sagitt** [humbertogontijo/homeassistant-roborock#290]
Hi, i using this due map limitation on official xiaomi integration.

i have a roborock s6 maxv, but i can't see sensors:

- total clean area
- total clean duration
- total clean count
- last clean area
- last clean time
- last clean start
- last clean end

all other sensors works

plus this, there is a way to change colors on the map like xiaomi cloud map extractor?

**Comment by humbertogontijo** [comment]
Can you provide debug logs of the integration starting up? More specifically for command get_clean_summary request and response

**Comment by humbertogontijo** [comment]
Add to your logger in configuration.yaml 
logger:
  roborock: debug
  custom_components.roborock: debug

Restart HA and search for Roborock in system -> logs page

**Comment by Lash-L** [comment]
@humbertogontijo I thought you had a check in get_clean_summary for if it was an int. Was something wrong with that approach?
            elif isinstance(clean_summary, int):
                return CleanSummary(clean_time=clean_summary)

**Comment by humbertogontijo** [comment]
I think we might need to get that back, yeah
