### ISSUE TITLE
When Roborock S7 MaxV gets stuck its status is "Error" and after resume status did not update

### ISSUE THREAD

**Issue by wila91** [humbertogontijo/homeassistant-roborock#30]
When Roborock S7 MaxV gets stuck its status is "Error"

I tried to figure out where i could read logs for this but I couldn't find it in homeassistant. 

In offical Roborock app the notification was "Roborock S7 MaxV: Robot trapped. Clear away any obstacles surrounding it"

if necessary, I can reproduce the error. Just let me know what you need.

Also noticed that after getting stuck and status set to "error" after a little while status changed to "Charger disconnected" that is fine but after i came home and clicked on the robot to resume status did not change while cleaning.

When it went  back at the dock for cleaning the mop status was still "Charger disconnected" until i manually reloaded it in Integrations. After that status changed to "Washing the mop" ass it should

**Comment by humbertogontijo** [comment]
Were you using the latest release? Yesterday I released a version fixing the status not being updated.
About the message I am about to release some extra attributes. That might help finding which attribute relates to the message you are saying

**Comment by humbertogontijo** [comment]
Hmm, so the error code 8 is probably what maps to this message. I'll create a mapping for this error codes so they are shown as text

**Comment by wila91** [comment]
Here are few more possible errors  if you are mapping them.

![roborock errors](https://user-images.githubusercontent.com/102232162/208749570-a1446c64-9d37-4b40-b127-7144f6209f89.jpg)
Source: [Roborock User Manual](https://support.roborock.com/hc/en-us/article_attachments/6287880640281/Roborock_S7MaxV_Ultra_FCC_User_Manual.pdf)

**Comment by humbertogontijo** [comment]
Attribute error_text added to vacuum entity
