### ISSUE TITLE
Roborock S8 - Incorrect Time Left with Main Branch

### ISSUE THREAD

**Issue by stickpin** [humbertogontijo/homeassistant-roborock#300]
## Version of the custom_component

Main Branch
python-roborock v0.14.1

## What vacuum are you using?

Roborock S8

## Describe the bug

Incorrect time left is shown with the main branch.

![Screenshot 2023-05-09 at 16 35 04](https://github.com/humbertogontijo/homeassistant-roborock/assets/630000/59a58463-35de-46bb-91b4-6ff7bad0d0a3)

![IMG_3815](https://github.com/humbertogontijo/homeassistant-roborock/assets/630000/f9b92cc9-a7a5-4a54-8676-b41537608abf)

Any suggestion?

**Comment by stickpin** [comment]
Actually, those funny values are coming from get_consumable:
`2023-05-09 16:52:57.301 DEBUG (MainThread) [roborock.local_api] id=90073 Response from get_consumable: {'main_brush_work_time': 9816, 'side_brush_work_time': 9816, 'filter_work_time': 9816, 'filter_element_work_time': 0, 'sensor_dirty_time': 9751, 'dust_collection_work_times': 0}`

**Comment by Lash-L** [comment]
This should be resolved in the latest main

**Comment by stickpin** [comment]
@Lash-L thanks a lot! works as expected now! :)
