### ISSUE TITLE
Incorrect fan speeds in service roborock.vacuum_set_fan_speed

### ISSUE THREAD

**Issue by Dis90** [humbertogontijo/homeassistant-roborock#301]
## Version of the custom_component

main

## What vacuum are you using?

Roborock S6 Pure

## Describe the bug

Vacuum entity has correct fans speeds gentle, quiet, balanced, turbo, max but service roborock.vacuum_set_fan_speed has off, silent, balanced, turbo, max, max_plus, custom.

Is it possible to change service fans speeds match to entity?

## Debug log

```text

Add your logs here.

```

**Comment by humbertogontijo** [comment]
This service will be removed
