### ISSUE TITLE
Roborock on isolated wifi. 1.0.0

### ISSUE THREAD

**Issue by orrpan** [humbertogontijo/homeassistant-roborock#308]
## Version of the custom_component
1.0.0

## What vacuum are you using?

S7
## Describe the bug
My roborock is on an isolated wifi, so when this addon switch to only local I can not use it. Would it be possible to have cloud as backup on failure or as an option?

## Debug log

```text



```

**Comment by stevesreed** [comment]
I'll second this request. 

My Roborock was working great using the old method, but I cannot get this version to work.

I have the Roborock on a guest network that can see the internet, but not my home network, which is a very common setup for basic IoT network security.

I've added a hole in my firewall to allow the Roborock to talk to only to my HA server, but that does not seem to be enough. I cannot give Roborock full access to my private home network, so for now my only option is to roll back to the old version of this integration.

**Comment by humbertogontijo** [comment]
Thats odd. You prefer to have your device bounded to the company mqtt server? 
Most people do prefer to have control of their device locally so there is no dependency on the company goals and also avoid issues when there is no internet connection

**Comment by orrpan** [comment]
Yeah that would be the preferred way, but since the device does not work without internet and by default help the company goals I preferred to not let it be on my network :) (This can be old news/false and I'm banging out of order, if so I'm sorry).

The best solution I guess is [Valetudo](https://valetudo.cloud/), but since the S7 requires disassemble I do not have time time to go for it... But using this add-on with isolated wifi and tru cloud has been the second best solution :)

**Comment by AndLindemann** [comment]
I faced the same issue as I also have my Roborocks in a separate IoT Wifi which is locked down.
Certainly a note during the upgrade would've been nice, that such setups would be broken. I believe it's actually common practice to have the IoT things separated, so this shouldn't be an unusual setup.
For me, I'm lucky that I run HAOS on Proxmox. I just added a network interface for my IoT VLAN to the VM and now HA can talk to the Roborocks - yes, that exposes HA a bit on the IoT network, but it can easily be controlled through the Proxmox internal firewall.

**Comment by FluffyGhoster** [comment]
I have my HA over a VPN connection, so using the cloud connection was the only feasible way to have the integration; Would it be possible to have it back as it was before, selectably?

**Comment by Theetjuh** [comment]
Same here, got the S7 in a separated network, which worked perfectly with the previous implementation, but not with the new one.
Would love if there was an option to use the old way, cause I’m not letting the S7 in my normal network.

**Comment by Badbandit69** [comment]
Same here, my S8 will stay in a seperated VLAN.

**Comment by orrpan** [comment]
@humbertogontijo sorry for only whining and not doing PR myself, but are there any chance of this happening? Otherwise I'll see if there is any solution putting an old pi only for this on my isolated wifi and using remote-homeassistant or wireguard-client

**Comment by martijnve** [comment]
I have the same issue. As a rule of thumb, any device I cannot completely disconnect from the cloud lives in isolation on my network as a means of shielding the rest of my network from any unwanted access through it.

For now I'm staying on 0.1.2 for this reason but a cloud option/fallback would be very nice.

**Comment by SpeedlimitsB** [comment]
same here . How to go back to 1.0.1 ? its not listed any longer

**Comment by SpeedlimitsB** [comment]
Same issue with 1.0.8:
MainThread) [roborock.local_api] Connecting to 192.168.80.28
2023-06-23 21:42:05.726 INFO (MainThread) [roborock.cloud_api] Disconnecting from mqtt
2023-06-23 21:42:05.730 INFO (Thread-10 (_thread_main)) [roborock.api] Roborock client disconnected

Its taking the local ip and not cloud

**Comment by orrpan** [comment]
> same here . How to go back to 1.0.1 ? its not listed any longer

You need to use 0.1.2 to have cloud working. Either you git clone the repo to custom_components and checkout 0.1.2 or download zipped repo with branch 0.1.2 and unpack it in custom_components
Google install custom components home assistant

**Comment by humbertogontijo** [comment]
V1.0.8 have an option to use cloud only

**Comment by SpeedlimitsB** [comment]
installed 0.1.2 and it works :-)
