### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by smartmatic** [humbertogontijo/homeassistant-roborock#313]
## Version of the custom_component

main branch

## What vacuum are you using?
Roborock S6 maxV

## Describe the bug

After update to Roborock release 1.0.0 i had trouble with my vacuum. So deleted it via HACS, restarted HA and downloaded main branch again. 

After that i am now no longer able to add the integration. I got this error:

## Debug log

Not possible to add integration. Debug log can not provided

I am getting this error when i try to add the integration

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Also this error is in the HA log

```text
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 12:02:52 (3 occurrences)
Last logged: 12:03:09

Unable to install package python-roborock==0.17.2: ERROR: Could not find a version that satisfies the requirement python-roborock==0.17.2 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11.dev0, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.11, 0.6.12, 0.6.13, 0.6.14, 0.6.15, 0.6.16, 0.6.17, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0rc0, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.14.1, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.3) ERROR: No matching distribution found for python-roborock==0.17.2 [notice] A new release of pip is available: 23.1 -> 23.1.2 [notice] To update, run: pip install --upgrade pip

```

**Comment by humbertogontijo** [comment]
Try downloading main again. It now using another version of python-roborock

**Comment by smartmatic** [comment]
Re-download worked. Could successfully add the integration again.
One warning is since some days also my logs:

Logger: roborock.code_mappings
Source: runner.py:179
First occurred: 12:36:27 (3 occurrences)
Last logged: 12:37:19

Missing RoborockFanSpeedE2 code: 102 - defaulting to 41

**Comment by humbertogontijo** [comment]
Could you add your device here https://github.com/humbertogontijo/homeassistant-roborock/issues/261 ?

**Comment by smartmatic** [comment]
> #261

yes, sure, i've updated #261 with the S6 maxV types for fan speed and mop intensity.
