### ISSUE TITLE
Failure calling xiaomi_miio/vacuum_clean_zone. Service not found

### ISSUE THREAD

**Issue by Brouwertje** [humbertogontijo/homeassistant-roborock#316]
I migrated from Miio, deleted Miio integration. I'm using Roborock now. 

Why is the service call for clean zone not working? I'm not using the Miio service call and yet it gives this error.

![afbeelding](https://github.com/humbertogontijo/homeassistant-roborock/assets/89314233/c21d87d8-780f-4fa8-86b8-5cd19a4ca929)

service: roborock.vacuum_clean_zone
data:
  zone:
    - - 21961
      - 28594
      - 23179
      - 30622
      - 1
target:
  entity_id: vacuum.roborock_s7_2

**Comment by Lash-L** [comment]
I'd restart your home assistant again and clear your cache. Sometimes home assistant will still link with old versions of an integration and cause weird bugs like that

**Comment by humbertogontijo** [comment]
This is super odd. You are calling roborock.vacuum_clean_zone and it is complaining about xiaomi_mio??

**Comment by Brouwertje** [comment]
Ok, clearing Cache did not help. I tried it in Edge (never used it for HA) and it worked. So it's a cache issue on my end. Sorry! Thanks for the quick replies.
