### ISSUE TITLE
Missing RoborockFanSpeedE2

### ISSUE THREAD

**Issue by Boss-man** [humbertogontijo/homeassistant-roborock#327]
## Version of the custom_component
1.0.1

## What vacuum are you using?
Roborock S6 MaxV

## Describe the bug
After updating to 1.0.x I get this warning in the debug log every 30 mins

`WARNING (MainThread) [roborock.code_mappings] Missing RoborockFanSpeedE2 code: 103 - defaulting to 41`

**Comment by 108085** [comment]
`WARNING (MainThread) [roborock.code_mappings] Missing RoborockFanSpeedE2 code: 102 - defaulting to 41`

Got kind of the same message (same vacuum)

`Response from get_status: {'msg_ver': 2, 'msg_seq': 2069, 'state': 8, 'battery': 100, 'clean_time': 3657, 'clean_area': 64950000, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0, 'in_returning': 0, 'in_fresh_state': 1, 'lab_status': 3, 'water_box_status': 1, 'fan_power': 102, 'dnd_enabled': 0, 'map_status': 11, 'is_locating': 0, 'lock_status': 0, 'water_box_mode': 202, 'distance_off': 60, 'water_box_carriage_status': 1, 'mop_forbidden_enable': 1, 'camera_status': 421, 'is_exploring': 0, 'home_sec_status': 0, 'home_sec_enable_password': 1, 'adbumper_status': [0, 0, 0]}`

**Comment by Lash-L** [comment]
Hi - can you change your fan speed codes one at a time in the app, then get the result go get status? Tell me what number in fan speed code corresponds with what name in the app?

**Comment by 108085** [comment]
@Lash-L 

101 - Quiet
102 - Balanced
103 - Turbo
104 - Max
105 - Gentle | Single-Use only

**Comment by Boss-man** [comment]
Same error on 1.0.2, but don't know if that version contained any fixes for this.

**Comment by Boss-man** [comment]
Still the same on version 1.0.3

**Comment by Lash-L** [comment]
Try the new version, 1.0.4

**Comment by Boss-man** [comment]
1.0.4 seems to work :)
