### ISSUE TITLE
Roborock sensors reset buttons have no effect on value

### ISSUE THREAD

**Issue by Fredzxda** [humbertogontijo/homeassistant-roborock#330]
Hello,
Button of the integration to reset sensors value doesn't work for my roborock S7
![Sensors reset](https://github.com/humbertogontijo/homeassistant-roborock/assets/37531742/0654d02a-9317-4ebb-9a3f-ea38776c9e32)
![Sensors value](https://github.com/humbertogontijo/homeassistant-roborock/assets/37531742/ed10ec1c-2890-410f-972e-3085db1344e1)
No error on logs as I can see.

**Comment by humbertogontijo** [comment]
It is resetting. There is just an issue with the sensor where it's not updating when the filter time is 0. It will be fixed in next release

**Comment by Lash-L** [comment]
@Fredzxda are you still having issues?

**Comment by Fredzxda** [comment]
Will have a look this weekend and let you know

**Comment by Fredzxda** [comment]
It works now like a charm. You can close the issue.
Thank a lot.
