### ISSUE TITLE
Dock status no longer shows errors

### ISSUE THREAD

**Issue by martinj27** [humbertogontijo/homeassistant-roborock#339]
The dock status used to show the current state but now it only says on or off

**Comment by vveidenberg** [comment]
For S7 MaxV Ultra, the DockErrorStatus value is always 0. It would be very helpful if it could give error if dock water tank is empty.

**Comment by humbertogontijo** [comment]
Will be fixed by https://github.com/humbertogontijo/homeassistant-roborock/commit/3ae0cb72cb9ce042fd6f500e37805390825cabf3
