### ISSUE TITLE
Some automation/script examples for HA

### ISSUE THREAD

**Issue by poudenes** [humbertogontijo/homeassistant-roborock#342]
## Is your feature request related to a problem? Please describe.
Not related to a problem

## Describe the solution you'd like
Maybe add some examples for automations in HA (im using the S8)

I'm new with this integration and create many automations. But I don't see any (for now) useful services to start te roborock to clean to house. There are some services for zone or spot. you need to give the X,Y Coordinates or 4 point zone information. 

(Where to find those?) Can I add the zone name also? lots of questions.

Then we have a vacuum entity with many options: start, pauze, stop, clean stop locate and return home.
A pull down for fan speed.

Those options I can't find a service to run them when search on "Roborock" (logical for me). But when you search for vacuum in service list then there are more options. 

SO maybe some nice automations, scripts examples to help new users a bit how to use all those new entities would be nice.

//Keep up the good work!!

**Comment by poudenes** [comment]
I have implement my S8 fully in HA with some automation's:

- When people leaves to house clean the house on Mon, Wed, Fri, deep clean etc. Otherwise balanced etc.
- Create automation that will trigger when you ask Alexa to clean the house or a room
- Same automation will use to trigger when you ask HomeKit (siri) to clean the house or room
- Monitor when filters, sensors, brushes need to be cleaned or replaced.

If interested i can share them with you to add this on your page.

**Comment by superpower10** [comment]
@poudenes 
I‘m interested would love to see automations with set cleaning an mop modes.

Thank you very much

**Comment by Scirazza** [comment]
@poudenes thank you very much!
Thats really great?
