### ISSUE TITLE
No device found within your Roborock account

### ISSUE THREAD

**Issue by valuta1995** [humbertogontijo/homeassistant-roborock#343]
## Version of the custom_component
1.0.3

## What vacuum are you using?
Roborock S7 (roborock.vacxuum.a15)

## Describe the bug
With the S7 configured in the app (and functioning, and online) the integration will say that "No device found within your Roborock account" regardless of password/code login.

## Debug log
Cannot enable debug logging because the plugin will not configure.
```text
N/A
```

**Comment by Lash-L** [comment]
Are you using the Roborock account and not the mi home app?

**Comment by Lash-L** [comment]
Download the Roborock app and set the vacuum up there instead of the mi home app
