### ISSUE TITLE
Feature Request - Exposing child lock

### ISSUE THREAD

**Issue by notorioustubze** [humbertogontijo/homeassistant-roborock#356]
Is it at all possible to expose the child lock setting? My one year old loves to turn my vacuum on and attempt to ride it around the house. It would be awesome to have the option exposed so I could set an automation in HA to disable and enable the mode based on when he is awake and asleep.

Roborock S7

**Comment by Lash-L** [comment]
Yes :) - I added it to the core integration and I plan on adding it here as well.

**Comment by notorioustubze** [comment]
Wonderful! my robot will be very happy :) thank you for all the great work!

**Comment by Lash-L** [comment]
I believe this was added
