### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by oleg-78** [humbertogontijo/homeassistant-roborock#36]
Hello.
I updated the program, I also updated the Roborock custom component.
After the update, the integration broke.

Logger: homeassistant.config_entries
Source: custom_components/roborock/api.py:165
Integration: Roborock (documentation, issues)
First occurred: 9:59:40 AM (3 occurrences)
Last logged: 10:09:39 AM

Error setting up entry Roborock S7 MaxV for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 30, in async_setup_entry
    client = RoborockMqttClient(user_data, home_data)
  File "/config/custom_components/roborock/api.py", line 165, in __init__
    for device in home_data.get("devices") + home_data.get("receivedDevices"):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by humbertogontijo** [comment]
You need to remove the integration from the Devices & Services and add it again. Its using an email 2FA authentication now instead of the password

**Comment by oleg-78** [comment]
Thank you
