### ISSUE TITLE
Use Pin&Go (GoTo) Service

### ISSUE THREAD

**Issue by myreal84** [humbertogontijo/homeassistant-roborock#364]
## What vacuum are you using?
Roborock S7

## Describe the bug

I am new to HomeAssistent i guess its not a bug, i guess its me.

I dont know how to get the Service "GoTo" 
I dont see it in the Integrations Tab
And i never added something like this befor via YAML

Can any one please explain or is it just not an option for S7

**Comment by n0tOdd** [comment]
This is my automation for making the s7 go to my kitchen

`service: roborock.vacuum_goto
data:
  x_coord: "26252"
  y_coord: "30640"
target:
  entity_id: vacuum.roborock_s7
`

The x/y coordinate I got with the  "xiaomi vacuum map card"  integration found in hacs

**Comment by zhuodong45** [comment]
Could you explain how to get the x/y from the map card? I am using it, but i don't see it

**Comment by n0tOdd** [comment]
put the pin and go button where u want it and press the play button for 5 sec and you will get a popup with the info

**Comment by myreal84** [comment]
> This is my automation for making the s7 go to my kitchen
> 
> `service: roborock.vacuum_goto data: x_coord: "26252" y_coord: "30640" target: entity_id: vacuum.roborock_s7 `
> 
> The x/y coordinate I got with the "xiaomi vacuum map card" integration found in hacs

Im so new to all this that i don`t even understand where to place this.
Tried to find Tutorials but i dont get it.
can you give a short explaination?

THANK YOU
