### ISSUE TITLE
Error after Update top 0.0.1 dir S7MaxV

### ISSUE THREAD

**Issue by hammelkopp** [humbertogontijo/homeassistant-roborock#37]
Hi, before updating top 0.0.1 everything worked fine so far. Now I got an error and the integration is broken.

Logger: homeassistant.config_entries
Source: custom_components/roborock/api.py:165
Integration: Roborock (documentation, issues)
First occurred: 16:41:08 (1 occurrences)
Last logged: 16:41:08

Error setting up entry Roborock S7 MaxV for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 30, in async_setup_entry
    client = RoborockMqttClient(user_data, home_data)
  File "/config/custom_components/roborock/api.py", line 165, in __init__
    for device in home_data.get("devices") + home_data.get("receivedDevices"):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by kristofferR** [comment]
0.0.1 is a breaking change, you need to remove the Roborock integration and add it again.

**Comment by hammelkopp** [comment]
Thx, it's working again!

**Comment by hammelkopp** [comment]
.
