### ISSUE TITLE
Missing RoborockDockErrorCode code: 44

### ISSUE THREAD

**Issue by shbatm** [humbertogontijo/homeassistant-roborock#378]
## Version of the custom_component

1.0.6 on HA 2023.6.1

## What vacuum are you using?

Roborock S7 MaxV Ultra

## Describe the bug

Missing dock code 44 for a dirty tank latch not closed or a plugged filter: 

![Screenshot_20230613_093951_Roborock](https://github.com/humbertogontijo/homeassistant-roborock/assets/18057952/6274e1f5-1d6b-4aca-aec6-db5e339274de)

## Debug log

```text

Logger: roborock.code_mappings
Source: runner.py:179
First occurred: 9:17:35 AM (28 occurrences)
Last logged: 9:31:05 AM

Missing RoborockDockErrorCode code: 44 - defaulting to 0

```

**Comment by Lash-L** [comment]
Would you mind doing the same for all of the latches? Get me all of the error codes

**Comment by shbatm** [comment]
I'll see what I can do, I tried getting the error for missing clean water tank and it didn't want to report anything (red dock light was on though), but I didn't have much time to mess with it. 

Also, would it be possible to add a generic error? Defaulting to 0 indicates nothing wrong for an unknown error number.

**Comment by Lash-L** [comment]
I would create the error, then try to do something in the app like clean or perform a dock option

As far as a default error - I may be able to make something work

**Comment by Lash-L** [comment]
Sounds good - Error 44 should be added.
