### ISSUE TITLE
Banned from roborock

### ISSUE THREAD

**Issue by martinj27** [humbertogontijo/homeassistant-roborock#383]
## Version of the custom_component
1.0.6

## What vacuum are you using?
I am using the s7 maxv ultra

## Describe the bug
I was setting up and automation to send the robot back to the dock, but it seems that when I sent the dock command, I got banned by roborock (I used  Action
Let roborock s7 maxv return to the dock)

**Comment by Lash-L** [comment]
What do you mean by banned by roborock?

**Comment by martinj27** [comment]
I can't connect the robot to my home network since I've been banned by roborocks servers, it works on other networks

**Comment by andonevris** [comment]
I had to restart HA after an OS update and when it came back up the roborock integration would not log in.

After a lot of messing around I came across this post and tried rebooting my router to get a new public IP address soon as it came back up the integration logged in straight away.

I think Roborock may be banning IPs for some reason?

**Comment by rschoell** [comment]
also applies to my install. Cannot change the external IP and happens since the HA OS Update to 10.3.
Any fix would be much appreciated

**Comment by Lash-L** [comment]
The issue stems from the map client. If you are fine without the map, I would switch to the core integration, as at the moment that is 100% local and no chances of being banned. I believe we have some changes relating to the map coming on the custom integration, so I would hold tight.

**Comment by prometheanfire** [comment]
ya, can't access https://usaccount.roborock.com/ here either (useful as a test)

**Comment by rschoell** [comment]
Dongrading to 1.0.6 helped me.



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Matthew Thode ***@***.***>
Datum: 22.06.23 00:15 (GMT+01:00)
An: humbertogontijo/homeassistant-roborock ***@***.***>
Cc: surfer2100 ***@***.***>, Comment ***@***.***>
Betreff: Re: [humbertogontijo/homeassistant-roborock] Banned from roborock (Issue #383)


ya, can't access https://usaccount.roborock.com/ here either (useful as a test)

**Comment by martinj27** [comment]
> ya, can't access https://usaccount.roborock.com/ here either (useful as a test)

Weirdly I can still access the roborock website and login, but the vacuum is unable to on the same network.

**Comment by martinj27** [comment]
I got this figured out, it ended being something triggered my network controller to block the robot from connecting to the wifi

**Comment by prometheanfire** [comment]
What was being blocked?  What change was needed to get the vacuum connected?

**Comment by martinj27** [comment]
It somehow got mac address banned from the local network, I'm not sure why, I wasn't even aware that the omada network controller would auto ban devices
