### ISSUE TITLE
Unable to add integration (passwordless)

### ISSUE THREAD

**Issue by Nezz** [humbertogontijo/homeassistant-roborock#39]
I updated to the latest version with the passwordless login. I removed the old integration and tried to add the new one, but it's failing:
![image](https://user-images.githubusercontent.com/431167/209188664-5df8e2df-d8c5-4651-8229-50aa52f49c26.png)

By the way, the input field before that said "Username" but I had to enter my email.

**Comment by humbertogontijo** [comment]
Are there any logs?

**Comment by Nezz** [comment]
I restarted HA one more time and then it worked. Still had to use my email as the username.

I checked the logs when the failure happened and there is nothing relevant.

**Comment by humbertogontijo** [comment]
I'll update the config translation. It should be the email
