### ISSUE TITLE
Logger: roborock.api

### ISSUE THREAD

**Issue by nikrays** [humbertogontijo/homeassistant-roborock#395]
Logger: roborock.api
Source: /usr/local/lib/python3.11/site-packages/roborock/api.py:233
First occurred: 03:59:20 (2 occurrences)
Last logged: 03:59:57

unsupported operand type(s) for 'in': 'int' and 'EnumType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 226, in on_message_received
    elif data.payload and protocol in RoborockDataProtocol:
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 739, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'int' and 'EnumType'

**Comment by nagydavid** [comment]
Same here

**Comment by CH1PSET1** [comment]
Same here

**Comment by humbertogontijo** [comment]
Should be fixed in v1.0.9
Feel free to open another one otherwise
