### ISSUE TITLE
VacuumEntityFeature.MAP?

### ISSUE THREAD

**Issue by ckdo8008** [humbertogontijo/homeassistant-roborock#4]
Hello~
Thanks for making it.

It is set to include the map.
It doesn't seem to provide a map.

**Comment by humbertogontijo** [comment]
It is on my roadmap, but I removed the feature VacuumEntityFeature.MAP  for the time being

**Comment by SVNKoch** [comment]
@humbertogontijo you mind publishing the roadmap somewhere? Maybe some people can then help developing these features ;)
