### ISSUE TITLE
Map change

### ISSUE THREAD

**Issue by flo2126** [humbertogontijo/homeassistant-roborock#404]
Hello
I have a Roborock S7 with 2 maps.  Version of the roborock integration is 1.0.8.
How can I change the maps? 
If I change it in Roborock App it also changes in Home Assistant. But I would like to do that in Home Assistant. 
I read something about the map sensor but somehow I don't understand it.

Many thanks for the help

**Comment by humbertogontijo** [comment]
Use service roborock.vacuum_load_multi_map
