### ISSUE TITLE
"Valley" Electricity

### ISSUE THREAD

**Issue by Mikescotland** [humbertogontijo/homeassistant-roborock#412]
Thanks for awesome work.
Just a suggestion. Currently there is "Valley electricity" translation which refers to charging outside expensive peak hours.
I'd suggest changing it to "off-peak electricity" as "Valley" doesn't make much sense in this case.
Thanks!

**Comment by Lash-L** [comment]
We typically follow the actual command name.

We didn't name it valley, but rather Roborock themselves did.

I would agree off peak would probably make more sense, so we can potentially change it in the future

**Comment by shred86** [comment]
Yeah, this command name is definitely odd. I also think renaming it to align with the Roborock app would make more sense, which is "Off-Peak Charging".

Along the same lines, what is the "Flow led status"? Is that supposed to be what's titled as "Status Indicator Light" in the Roborock app? If so, I think maybe aligning this would make more sense too.

**Comment by humbertogontijo** [comment]
Changed their names. Will be available in next release https://github.com/humbertogontijo/homeassistant-roborock/commit/15141741c1b734b364e15100e3c23532d6cae1b0
