### ISSUE TITLE
A question about the sensors and the key figures

### ISSUE THREAD

**Issue by clipse2004** [humbertogontijo/homeassistant-roborock#44]
Hi, 

first of all, you are my savior! Hammer awesome that you got the integration done, I've been waiting forever! 
Do you mean the sensors to the filter etc. you get also still? 

Do you have an overview of what the numbers behind the attributes mean? 
For example at water_box_status or water_box_carriage_status. Currently, I have a 1, which means that the water tank is good. And if there is 0 then it should be filled, do I understand that correctly?

I want to create the sensors individually via templates. 

Thank you!

**Comment by humbertogontijo** [comment]
I've added some sensors that I know the meaning to the integration

**Comment by clipse2004** [comment]
And where did they Show? 
under the Integration i only have two entities.
One for vacuum and one for Camera.

**Comment by humbertogontijo** [comment]
v0.0.4 is needed

**Comment by humbertogontijo** [comment]
Is it fixed for you now @clipse2004 ?

**Comment by clipse2004** [comment]
Yep sorry i forgot to close
