### ISSUE TITLE
can`t pass "starting configuration"

### ISSUE THREAD

**Issue by Ifarh** [humbertogontijo/homeassistant-roborock#47]
when I'm trying to install the integration it does not pass the first "starting configuration", like in the picture. restart was tried and also tried a few tims
![‏‏לכידה](https://user-images.githubusercontent.com/56223127/209482434-dd414259-7a96-4ebd-8900-a7917fbaf3e1.JPG)

**Comment by humbertogontijo** [comment]
This could be a library incompatibility. But to be honest this is highly likely an internet issues and not a dependency problem

**Comment by Ifarh** [comment]
![Capture](https://user-images.githubusercontent.com/56223127/209518076-e01bb3c4-b999-4778-891e-a0a730fd6c51.PNG)

some time I get this message, i`ll try to reinstall and restart the router

**Comment by Ifarh** [comment]
solved by reinstall
