### ISSUE TITLE
Delayed Vacuum State Update

### ISSUE THREAD

**Issue by mich1978** [humbertogontijo/homeassistant-roborock#518]
[home-assistant_roborock_2023-10-21T05-17-35.261Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/13059894/home-assistant_roborock_2023-10-21T05-17-35.261Z.log)

## Version of the custom_component
1.0.12

Home Assistant Version:
2023.10.3

## What vacuum are you using?
Roborock S8+

## Describe the bug

There is a noticeable lag in the update of the current state of the vacuum.  In the previous version of the integration when the vacuum was finished cleaning the state would change to 'returning' within 30 seconds, often times more like 10 seconds.  Currently it is about 2 minutes until an update in the state is made.  By then the state is 'docked.'

I was using the state of the vacuum in an automation so when it would finish cleaning a zone, I could call on it to clean a room.  Since the 'returning' state is not reporting the automation fails.

When I look in the history it shows it updated to 'returning' 1 minute before it shows 'docked' but the current state doesn't reflect that.

Thanks again for this awesome integration. 👍 
## Debug log

```text

Add your logs here.
[home-assistant_roborock_2023-10-21T04-58-14.524Z.log](https://github.com/humbertogontijo/homeassistant-roborock/files/13059872/home-assistant_roborock_2023-10-21T04-58-14.524Z.log)


```

**Comment by iddiek** [comment]
Same here.
Strange thing: if I change integration to xiaomi_miio using the same Sg server the problem persist. No problem with cn server and other xiaomi_miio vacuum so probably is also server related

**Comment by xnisayx** [comment]
Same issue as in https://github.com/humbertogontijo/homeassistant-roborock/issues/437

**Comment by KuChar91** [comment]
Same here.

**Comment by neforce** [comment]
Same issue here. I can remember that a month or 2 ago, it worked quite fine here. But suddenly it has a huge delay (25 sec?).

I'm using the state for a customized 'Intense cleaning' option;

Cleaning -> returning to dock? -> restart zone cleaning, but with Deep+ Mop only.

But that's not doable now....

**Comment by modo1302** [comment]
same here! all the states (including current room) take over a minute or two to update.

**Comment by Tsarre** [comment]
same here with Roborock Q8 Max Plus

**Comment by crhammock** [comment]
I have the same issue as of a few weeks ago.  Not sure if it was a HACs update or something roborock have changed but it is causing issues with some of my automations.  Using Roborock S7

**Comment by neforce** [comment]
I'm also experiencing the same delay with the original Roborock app. When the S7 is finished and already docked. I'm getting the notification: "finished cleaning, returning to dock" i guess it's not only HA

**Comment by modo1302** [comment]
> I'm also experiencing the same delay with the original Roborock app. When the S7 is finished and already docked. I'm getting the notification: "finished cleaning, returning to dock" i guess it's not only HA

Nope, for me the original Roborock app works fine. Definitely an issue on the integration side.

**Comment by iddiek** [comment]
> > I'm also experiencing the same delay with the original Roborock app. When the S7 is finished and already docked. I'm getting the notification: "finished cleaning, returning to dock" i guess it's not only HA
> 
> Nope, for me the original Roborock app works fine. Definitely an issue on the integration side.

I Agree. Hope to see assignees too, maybe would be better open issues in homeassistant repo

**Comment by mindgam3s** [comment]
experiencing the same problems and this breaks my automations :(

**Comment by wigster** [comment]
I will just add that this delayed behaviour used to be how the integration worked until around 1.0.5, when some timeouts were fixed. Then on my S7, the state updates where instantaneous until the upgrade to 1.0.12.  Maybe this is just a coincidence, but could there have been some reversion?

**Comment by Lash-L** [comment]
Hi I should have a fix coming for this once I have a chance to fully implement it.

We have 'listeners' that are able to update some information automatically as it is 'published' using the cloud connection. I'm changing how it works a bit under the hood, but I should have something out this week.

**Comment by mich1978** [comment]
> Hi I should have a fix coming for this once I have a chance to fully implement it.
> 
> We have 'listeners' that are able to update some information automatically as it is 'published' using the cloud connection. I'm changing how it works a bit under the hood, but I should have something out this week.

Thanks! 👍

**Comment by Lash-L** [comment]
Try the latest main version

**Comment by crhammock** [comment]
preliminary testing seems the problem is solved, state updates are now almost instant (which means my automations are working better).  I didn't have time this morning to do a thorough test so see what everyone else thinks

**Comment by neforce** [comment]
i've downloaded the updated main too. I'll try our S7 when i'm back home later today.

**Comment by mindgam3s** [comment]
> Try the latest main version

My installation does not show me any updates I'm missing.
Is there a way to force said update?

**Comment by neforce** [comment]
> > Try the latest main version
> 
> My installation does not show me any updates I'm missing. Is there a way to force said update?

go to hacs -> search for the roborock integration -> three dots upper right -> reinstall software -> wait a bit for it to download all tags -> choose main branch.

**Comment by crhammock** [comment]
> > > Try the latest main version
> > 
> > 
> > My installation does not show me any updates I'm missing. Is there a way to force said update?
> 
> go to hacs -> search for the roborock integration -> three dots upper right -> reinstall software -> wait a bit for it to download all tags -> choose main branch.

related question, does anyone know why this is the case?  It is something that has been bugging me for a while, is there some sort of schedule task in HA which checks HACS repos?  Seems strange that it isn't instant or more frequent to prompt for new updates available.

Obviously this has nothing to do with this specific integration I am just curious

**Comment by wigster** [comment]
It checks on HA restart and at some point during the night, once per day. There is a sensor you can use to see how many HACS integrations have upgrades available (sensor.hacs).

**Comment by crhammock** [comment]
so there is, thanks @wigster

**Comment by neforce** [comment]
Tried the main update, and it works!!! You are so great man! Here, grab a beer!

**Comment by modo1302** [comment]
Hey, the state updates are instant for me too. Is it possible to apply the same fix for the room update as well?

**Comment by Lash-L** [comment]
Room updates are unfortunately different.

There are certain things that we can get instantly and certain things we cannot.

If your vacuum broadcast anything that we currently aren't handling, then you will get a warning in the logs. But as far as the current room goes, the only way for us to get that is to get the map(which is an expensive call so we attempt to limit it)

**Comment by Tsarre** [comment]
Stupid, but "go to hacs -> search for the roborock integration -> three dots upper right -> reinstall software"

I don't have "reinstall software"... only "Repository - Update information - Redownload - Open issue - Request for removal - Remove'

**Comment by Tsarre** [comment]
Thanks, just wanted to be sure...

In the meantime I have tested it and I think I have found a problem: when you return the robot to its dock (vacuum.return_to_base) **during** cleaning (status: cleaning), you still get the delay.

**Comment by arne182** [comment]
I do not see any improvements on my S8 pro Ultra.

**Comment by Stardust0766** [comment]
I see the improvements with my S8 pro Ultra. ;-)
Have you really installed the latest **main** version?

**Comment by arne182** [comment]
Yes. I don't see it either in the vacuums attributes of in the dock status entity. Tested it with the vac dicken and also with it cleaning. What part of the code is making the status be updated?

**Comment by neforce** [comment]
Something odd is popping up. When i'm going to clean, no status update will arrive. However, as soon as i click; 'dock roborock', the state update will change to 'zoned cleaning'...

**Comment by mindgam3s** [comment]
> Something odd is popping up. When i'm going to clean, no status update will arrive. However, as soon as i click; 'dock roborock', the state update will change to 'zoned cleaning'...

I can confirm the states are even worse now ...
sometimes it doesnt update at all until I reload the integration or change the robots state by manuall giving it something to do (like changing fan_speed)

**Comment by erd82** [comment]
same for me ... around 35 seconds delay for state update

**Comment by modo1302** [comment]
hey, wasn't the status delay fix from two weeks ago included in the lates update? I've updated from main to 1.0.12 and the delays are back.

**Comment by mich1978** [comment]
I don't think that the "beta" or Hacs branch has seen a fix for this yet.  I updated to the main branch to test it out but it messed up a lot of my automations, and I couldn't see the "sensor.vacuum.current_room" at all. (I have a custom room card and I couldn't see the robot bounce back and forth on it).  I ended up going back to the Hacs version and am patiently waiting for an update.

**Comment by FerronN** [comment]
I updated to v1.0.13. I get instant state changes now :)

**Comment by neforce** [comment]
Yeah, ditto here. Updated to .13, restarted, and when i'm pressing 'clean', it instantly changes it states.

Thanks!

**Comment by xnisayx** [comment]
> I updated to v1.0.13. I get instant state changes now :)

And what happens if you change the fan speed? Does it also change immediately?

For me it doesn't.

**Comment by neforce** [comment]
Unfortunately it doesn't work anymore. Looks like it just worked once. When i start the vacuum, same issues again...

**Comment by mich1978** [comment]
Sorry for the late update, everything has been working great for me after the update to 1.0.13.  Thanks again to everyone who worked on a fix for this.  👍

**Comment by wigster** [comment]
S7 here -- indeed it seems to work immediately often (cleaning -> returning to dock is immediate) and without much delay for some others (e.g. fan change can take ~5-10 seconds to register)

**Comment by modo1302** [comment]
hi guys, after the 2024.5 update the state changes are lagging again. has anyone experienced this bug as well?

**Comment by Craig-97** [comment]
> hi guys, after the 2024.5 update the state changes are lagging again. has anyone experienced this bug as well?

Same issue for me, if the robot has been inactive for a while it can take over a minute to change state. My automations that relied on this are now useless. I have the Roborock Q7 Max+
