### ISSUE TITLE
More info for new users in readme

### ISSUE THREAD

**Issue by peteh** [humbertogontijo/homeassistant-roborock#54]
Hi, 

not sure if I missed it, but it would be cool to have a list of features and robots that are currently supported in the readme - especially compared to the original xiaomi ha integration. 

I have a 6 MaxV and wonder if I can use the integration to replace the xiaomi integration. 

I am using: 
 * map card
 * commanding specific rooms
 * locate
 * start/stop cleaning
 * return to dock

Is it possible to send this command for cleaning a list of rooms via this integration? 

```
{"command":"app_segment_clean","params":[..room ids..]}
```

**Comment by humbertogontijo** [comment]
Hello.
This integration have all you need, but Xiaomi integration is years ahead, meaning that this integration is still unstable. You can stick with a version that you find stable, but its up to you

**Comment by peteh** [comment]
Unstable as it sometimes stops working randomly or regularly breaks due to updates?

**Comment by humbertogontijo** [comment]
It can randomly stop working due to a bug or even break with an update since I'm releasing new features all the time

**Comment by peteh** [comment]
Alright, thanks for the heads-up and for putting in the work - I'm really looking forward to this integration. I'll come back in a few weeks then when I have a bit more free time and try and test it and give feedback as well. 

Is it possible to also read the camera stream from the robot and provide it as a cam to ha? It could be possible to actually add the remote control through a ha card in the future.

**Comment by humbertogontijo** [comment]
The remote control function is already achievable through this integration services. But unfortunately I still couldn't add the camera with the information I found online
