### ISSUE TITLE
"Padding is incorrect." error after upgrading the component

### ISSUE THREAD

**Issue by yllar** [humbertogontijo/homeassistant-roborock#55]
Upgrading from 0.0.3 to 0.0.6 made the robot and camera unavailable. The new sensors seem to work.
Model: a27
Location: EU 
```
Traceback (most recent call last):
  File "/config/custom_components/roborock/api.py", line 220, in on_message
    decrypted = unpad(decipher.decrypt(data.get("payload")[24:]), AES.block_size)
  File "/usr/local/lib/python3.10/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
```

**Comment by silkw0rm** [comment]
Did the same upgrade from 0.03 -> 0.0.6 and got the same result. The original entities for robot and camera are unavailable.
However there seems to have been created two unnamed entities. See screenshots.
Hope this can be fixed. Thanks in advance!
![2022-12-28 15_11_46-Overview – Home Assistant](https://user-images.githubusercontent.com/47475803/209825346-b98a7dc8-1c9d-4e51-99d3-0c11b3b8589b.png)
![2022-12-28 15_11_55-Overview – Home Assistant](https://user-images.githubusercontent.com/47475803/209825352-289250ba-c8e4-4a18-921c-e57ec745d770.png)

**Comment by Boss-man** [comment]
I see the same after going from 0.0.3 to 0.0.6.

```
ERROR (Thread-3 (_thread_main)) [custom_components.roborock.api] PKCS#7 padding is incorrect.
Traceback (most recent call last):
  File "/config/custom_components/roborock/api.py", line 220, in on_message
    decrypted = unpad(decipher.decrypt(data.get("payload")[24:]), AES.block_size)
  File "/usr/local/lib/python3.10/site-packages/Crypto/Util/Padding.py", line 95, in unpad
    raise ValueError("PKCS#7 padding is incorrect.")
```

**Comment by humbertogontijo** [comment]
Can you try removing the integration, restarting home assistant(So the unique ids are erased) e installing the integration again?

**Comment by yllar** [comment]
Yep, that worked. Thank you!
