### ISSUE TITLE
Google Calendar integration broken since HA 2023.11.3

### ISSUE THREAD

**Issue by hukoeth** [humbertogontijo/homeassistant-roborock#550]
## Version of the custom_component
1.0.12

## What vacuum are you using?

S7 MaxV

## Describe the bug
After update to HA version 2023.11.3, Google Calendar integration stopped working. The cause seems to be that Roborock integration pins ical to version 5.0.0 but the Google Calendar integration required 6.1.0 (or maybe 6.0.0?).
I found PR #545 open which should resolve the issue.
Manually changing the manifest.json solved the problem for me but not sure (yet) if there are any unintended consequences.

Bug for the Google Calendar integration is here
https://github.com/home-assistant/core/issues/104367

## Debug log

```text

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 10:34:41 (1 occurrences)
Last logged: 10:34:41

Setup failed for google: Unable to import component: No module named 'ical.exceptions'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
component = integration.get_component()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 816, in get_component
ComponentProtocol, importlib.import_module(self.pkg_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "/usr/src/homeassistant/homeassistant/components/google/init.py", line 10, in
from gcal_sync.api import GoogleCalendarService
File "/usr/local/lib/python3.11/site-packages/gcal_sync/api.py", line 40, in
from .model import (
File "/usr/local/lib/python3.11/site-packages/gcal_sync/model.py", line 18, in
from ical.exceptions import CalendarParseError
ModuleNotFoundError: No module named 'ical.exceptions'

```

**Comment by KentuckyMC** [comment]
Same issue here

**Comment by MiguelCosta** [comment]
Same issue. This integration is not compatible with [Home Assistant Core 2023.11.3](https://www.home-assistant.io/blog/2023/11/01/release-202311/#release-2023113---november-22).

https://github.com/home-assistant/core/pull/103759

**Comment by Lash-L** [comment]
Fixed in latest main branch 

@humbertogontijo - Calendar is a dead platform for you right? The whole thing should probably just be puled out

**Comment by Lash-L** [comment]
Nevermind - wont quite be fixed in latest main yet.

**Comment by humbertogontijo** [comment]
> Fixed in latest main branch
> 
> @humbertogontijo - Calendar is a dead platform for you right? The whole thing should probably just be puled out

Yes

**Comment by Lash-L** [comment]
Fixed in lastest main

**Comment by Phoenix-DH** [comment]
Has this already been released?
Can't find it.

Thanks.

**Comment by broyuken** [comment]
I upgraded to 1.0.13 and it's still giving me an error. HA 2023.11.3

```
Logger: homeassistant.components.google.calendar
Source: helpers/update_coordinator.py:322
Integration: Google Calendar (documentation, issues)
First occurred: 11:08:16 AM (1 occurrences)
Last logged: 11:08:16 AM

Error fetching xxxxxxxxxxx@gmail.com data: Error communicating with API: Failed to parse component: 1 validation error for Event attendees -> 1 CalendarBaseModel.__init__() got multiple values for argument 'self' (type=type_error)
```

**Comment by markrennie71** [comment]
Mine is the same, broken after upgrading to 1.0.13
