### ISSUE TITLE
Version 0.06 - Does not discover all of my devices

### ISSUE THREAD

**Issue by SethCalkins** [humbertogontijo/homeassistant-roborock#56]
Thanks for everyone on the development of this project. I've been here since the initial commit and everything has worked great (Haven't experienced any bugs) 

I updated to v0.06 today and had some issues. I removed the integration completely, and re-added.

When I signed back into Roborock only 1 out of the two devices were detected. It's missing my Roborock S7 MaxV Ultra. 

Any ideas?

**Comment by humbertogontijo** [comment]
Can you try removing the integration, restarting home assistant(So the unique ids are erased) e installing the integration again?

**Comment by SethCalkins** [comment]
> Can you try removing the integration, restarting home assistant(So the unique ids are erased) e installing the integration again?

Still nothing. All of the unique id's from the old device are gone... and still not adding

**Comment by SethCalkins** [comment]
Fixed in 0.08
