### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by CZonin** [humbertogontijo/homeassistant-roborock#564]
## Version of the custom_component
1.0.13

## What vacuum are you using?
SV MaxV Ultra

## Describe the bug
HA version 2023.12.1

I've been using the integration for awhile but today I noticed that my map was not loading so I tried reloading the integration, but still had the same issue. I tried removing the integration and re-adding it as that has solved issues for me in the past, but now after successfully entering my credentials, I get the error "Failed to set up" in the HA integrations page.

## Debug log

I don't have the option to enable debug logging, but here's the regular log:

```

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 6:18:48 PM (1 occurrences)
Last logged: 6:18:48 PM

Error setting up entry czonin5190@gmail.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/roborock/__init__.py", line 68, in async_setup_entry
    raise e
  File "/config/custom_components/roborock/__init__.py", line 58, in async_setup_entry
    home_data = await api_client.get_home_data(user_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/roborock/api.py", line 743, in get_home_data
    raise RoborockException(home_response)
roborock.exceptions.RoborockException: {'code': 'auth.err', 'msg': 'auth.err.invalid.token', 'status': 'UNAUTHORIZED', 'timestamp': '2023-12-09T23:27:10.571+00:00'}


```

**Comment by CZonin** [comment]
System time was not synced. Fixed that and now the integration works.

**Comment by garret** [comment]
Sorry I have the same issue. What do you mean for "system time" and how did you fix it exactly? thank you in advance!
