### ISSUE TITLE
0.0.9 not working for me

### ISSUE THREAD

**Issue by Brian-lub** [humbertogontijo/homeassistant-roborock#58]
Error writing config for core.config_entries: Failed to serialize to JSON: /config/.storage/core.config_entries. Bad data at $.data.entries[55].data.user_data=<custom_components.roborock.api.containers.UserData object at 0x7ff586513bb0>(<class 'custom_components.roborock.api.containers.UserData'>
09:27:42 – (ERROR) helpers/storage.py - message first occurred at 09:27:36 and shows up 2 times
Failed to serialize to JSON: /config/.storage/core.config_entries. Bad data at $.data.entries[55].data.user_data=<custom_components.roborock.api.containers.UserData object at 0x7ff586513bb0>(<class 'custom_components.roborock.api.containers.UserData'>
09:27:42 – (ERROR) util/json.py - message first occurred at 09:27:36 and shows up 2 times
Unexpected error fetching roborock data: 'int' object has no attribute 'get'
09:27:37 – (ERROR) Roborock (custom integration) - message first occurred at 09:19:27 and shows up 13 times
Roborock mqtt client disconnected (rc: 7)
09:27:36 – (ERROR) Roborock (custom integration) - message first occurred at 09:19:37 and shows up 12 times
Error setting up entry Roborock for roborock
09:27:35 – (ERROR) Roborock (custom integration)

**Comment by liamlain** [comment]
same not working after updated to latest 

Logger: homeassistant.helpers.storage
Source: helpers/storage.py:254
First occurred: 4:34:21 PM (2 occurrences)
Last logged: 4:35:34 PM

Error writing config for core.config_entries: Failed to serialize to JSON: /config/.storage/core.config_entries. Bad data at $.data.entries[77].data.user_data=<custom_components.roborock.api.containers.UserData object at 0x7f7b87ce80>(<class 'custom_components.roborock.api.containers.UserData'>

Logger: homeassistant.util.json
Source: util/json.py:88
First occurred: 4:34:21 PM (2 occurrences)
Last logged: 4:35:34 PM

Failed to serialize to JSON: /config/.storage/core.config_entries. Bad data at $.data.entries[77].data.user_data=<custom_components.roborock.api.containers.UserData object at 0x7f7b87ce80>(<class 'custom_components.roborock.api.containers.UserData'>

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/roborock/api/containers.py:284
Integration: Roborock (documentation, issues)
First occurred: 4:34:20 PM (1 occurrences)
Last logged: 4:34:20 PM

Error setting up entry Roborock for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/roborock/__init__.py", line 32, in async_setup_entry
    home_data = HomeData(await api_client.get_home_data(user_data))
  File "/config/custom_components/roborock/api/api.py", line 392, in get_home_data
    rriot = user_data.rriot
  File "/config/custom_components/roborock/api/containers.py", line 284, in rriot
    return RRiot(self.data.get(UserDataField.RRIOT))
AttributeError: 'UserData' object has no attribute 'get'

**Comment by medfiras** [comment]
Same not working after updated to latest 0.0.9
Deleted intergration and re-add still the same

**Comment by T-abr** [comment]
same problem with 0.0.9
Deleted integration and re-add still the same

**Comment by Aaronhrndz** [comment]
Same here

**Comment by humbertogontijo** [comment]
New release 0.0.10 should fix it

**Comment by Boss-man** [comment]
> New release 0.0.10 should fix it

Sorry.. just a new error

```
2022-12-29 13:25:00.951 ERROR (MainThread) [custom_components.roborock] Unexpected error fetching roborock data: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/roborock/__init__.py", line 80, in _async_update_data
    device_prop = await self.api.get_prop(device_id)
  File "/config/custom_components/roborock/api/api.py", line 320, in get_prop
    if len(clean_summary.records) > 0:
TypeError: object of type 'NoneType' has no len()
```
