### ISSUE TITLE
Error occurred loading flow for integration roborock

### ISSUE THREAD

**Issue by theautomation** [humbertogontijo/homeassistant-roborock#609]
## Version of the custom_component
1.0.13

## What vacuum are you using?
Roborock S6 and Roborock S5

## Describe the bug

I am getting an Error `occurred loading flow for integration roborock` when adding the integration -> Go to Settings->Devices & Services

## Debug log

I can't enable debug because it wont let me add the integration 

```text
Error occurred loading flow for integration roborock: cannot import name 'RoborockApiClient' from 'roborock.api' (/usr/local/lib/python3.12/site-packages/roborock/api.py)
```

**Comment by Lash-L** [comment]
If you're on the main version you shouldn't be.

Looks like you are on the latest python-roborock version which is a breaking change and I don't think the custom component has been updated to match it @humbertogontijo

**Comment by theautomation** [comment]
> If you're on the main version you shouldn't be.
> 
> Looks like you are on the latest python-roborock version which is a breaking change and I don't think the custom component has been updated to match it @humbertogontijo

I downloaded the latest version of this HACS integration and I am getting the same error. 

```text
Logger: homeassistant.config_entries
Source: config_entries.py:2444
First occurred: 12:40:21 (1 occurrences)
Last logged: 12:40:21

Error occurred loading flow for integration roborock: cannot import name 'RoborockApiClient' from 'roborock.api' (/config/deps/lib/python3.12/site-packages/roborock/api.py)
```
