### ISSUE TITLE
Sensor data missmatches with the app

### ISSUE THREAD

**Issue by toollu** [humbertogontijo/homeassistant-roborock#62]
The reported sensor data in HA does not align at all with the values from the app. "Main brush left", "filter left", "side brush left" report all the same value - which does not appear to match anything in the app. Also the "filter_left" value is wrong, although different from the  other values.

**Comment by Boss-man** [comment]
May I ask which Roborock model you have ?

**Comment by toollu** [comment]
> May I ask which Roborock model you have ?

It's a S7

**Comment by un5h4d0w** [comment]
I also have an S7 and am currently trying out this integration. For me, the values "Main brush left", "filter left" and "side brush left" correspond to the "Used" time (in the Roborocks app under Settings > Maintenance), this is why all of those values are the same I guess.

**Comment by jdejaegh** [comment]
I also have an S7 and what @un5h4d0w said makes sense in my case.  I just reset the value of the sensors and it says  `Roborock S7 Sensor dirty left: 0` in the integration.  I guess the sensor names are somewhat misleading.

**Comment by toollu** [comment]
@jdejaegh  @un5h4d0w Yes I can confirm that, the values seem to correspond to the "used" time in the app for each of the items. This also explains why the values match if the parts were never replaced. So the actual "xx_left" values would need to be calculated by a subtraction from what Xiaomi recommends. For the S7 this is:

Filter: 150h
Side brush: 200h
Main brush 300h
Sensors: 30h

Maybe those values are interesting for you @humbertogontijo . I don't know if those values are different for other models though.

I'm going to resolve this issue via templates in the HA FE directly until this is fixed. So far i managed to successfully use [this lovelace card](https://github.com/denysdovhan/vacuum-card) together with this integration. (I can share the code if anybody is interested).

**Comment by clipse2004** [comment]
> @jdejaegh @un5h4d0w Yes I can confirm that, the values seem to correspond to the "used" time in the app for each of the items. This also explains why the values match if the parts were never replaced. So the actual "xx_left" values would need to be calculated by a subtraction from what Xiaomi recommends. For the S7 this is:
> 
> Filter: 150h Side brush: 200h Main brush 300h Sensors: 30h
> 
> Maybe those values are interesting for you @humbertogontijo . I don't know if those values are different for other models though.
> 
> I'm going to resolve this issue via templates in the HA FE directly until this is fixed. So far i managed to successfully use [this lovelace card](https://github.com/denysdovhan/vacuum-card) together with this integration. (I can share the code if anybody is interested).

Sure please share :) 

For me, the app works since yesterday only sporadically :/ I must set up the daily at least 2x new.

**Comment by medfiras** [comment]
Hello,

i have an issue with sensor.roborock_main_brush_left. On HA i have  2949:25:22  instead of 249 hours on roborock app.
![HA](https://user-images.githubusercontent.com/1859595/210060410-12c0d0ea-b6c3-4b36-929f-66f840d80544.PNG)

**Comment by jdejaegh** [comment]
I noticed the same mismatch, it was introduced in [this commit](https://github.com/humbertogontijo/homeassistant-roborock/pull/65/commits/3890c2961e6fdbf851f977f966b1cf34b8ecfa7d#r1059391995), leading to an initial lifetime 10 times larger than what the app suggests.
