### ISSUE TITLE
Feature request: map rotation

### ISSUE THREAD

**Issue by Nezz** [humbertogontijo/homeassistant-roborock#73]
Could someone make it possible to configure the map rotation via the integration configuration UI? I can already change the rotation by altering `CONF_ROTATE: 0` in the code, so the underlying logic is already there - it just needs to be exposed as a configuration.

**Comment by Nezz** [comment]
Actually the Xiaomi plugin has this config group that would be nice to expose:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/blob/b4ae1d4bdd8268087cd269c7aeb2207a6dbefb2e/custom_components/xiaomi_cloud_map_extractor/camera.py#L79-L89

**Comment by shred86** [comment]
Looks like this was accomplished with the latest release 0.0.19. @humbertogontijo is doing some great work!

**Comment by humbertogontijo** [comment]
There is now a config option for some map properties

**Comment by adadnc** [comment]
Is this documented somewhere? I can't find any information how to rotate the map.

**Comment by humbertogontijo** [comment]
@adadnc hit the configure button for the integration(Within the config devices and services)

**Comment by adadnc** [comment]
> @adadnc hit the configure button for the integration(Within the config devices and services)

thank you!
