### ISSUE TITLE
interactive map not fully compatable

### ISSUE THREAD

**Issue by kubbur** [humbertogontijo/homeassistant-roborock#75]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/816497/210121190-5c8482d2-a92d-4e9c-8e56-a53fdac03da4.png">
cannot change fan speed, sometimes it changes to a higher setting, no errors anywhere, just doesn't work

**Comment by shred86** [comment]
This is going to be an issue with the [lovelace-xiaomi-vacuum-map-card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card). @Xyaren already [opened an issue](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/issues/518) on their GitHub to track the compatibility of that Lovelace card with this integration. However, with how early in development this integration is, there's still a lot changing almost daily so it may take a bit of time before things settle. In other words, I would probably expect to see more breaking changes but @humbertogontijo has been doing a tremendous amount of work so hopefully not too long before it's "stable". 😄

**Comment by kubbur** [comment]
Doh🤦‍♂️ ofc, thanks for letting me know
