### ISSUE TITLE
Timeout after 4 seconds waiting for get_map_v1 response

### ISSUE THREAD

**Issue by shred86** [humbertogontijo/homeassistant-roborock#77]
Receiving several of these when my vacuum was doing a segment cleaning (vacuum & mop) of two rooms. This is the S7 MaxV Ultra. I did open the app several times while it was cleaning but not sure if that's related to this. This also leads to the `Unable to retrieve map data` warning in camera.py:

````
2022-12-31 03:50:29.517 WARNING (MainThread) [custom_components.roborock.api.api] Timeout after 4 seconds waiting for get_map_v1 response
2022-12-31 03:50:29.519 WARNING (MainThread) [custom_components.roborock.camera] Unable to retrieve map data
````

I did notice while the vacuum is running, maps are being retrieved fairly quickly (every 5 seconds). Not sure if backing this off at all would help reduce these timeouts.

**Comment by humbertogontijo** [comment]
@shred86 I think was improve in the latest releases, right?

**Comment by shred86** [comment]
I haven't had a chance to test this yet so I wasn't sure. Since we're calling the `send` method within the `Camera` class itself, I assumed the changes to the coordinator `_async_update_data` method didn't apply here.

Speaking of the camera, I was thinking about trying to pull all the API code out of it but I wasn't sure how to best structure the camera code in the API. I was meaning to open a discussion post to see your thoughts on it.

**Comment by humbertogontijo** [comment]
The changes I made to reconnecting to mqtt is what I think that probably solved this

**Comment by shred86** [comment]
Ah okay, I'll mark as closed and re-open if I see the issue again.
