### ISSUE TITLE
Roborock S6 MAXV

### ISSUE THREAD

**Issue by isdedina** [humbertogontijo/homeassistant-roborock#78]
Hello, will it work with Roborock S6 MAXV? I tried it, but after some tome the device become unavailable...

**Comment by Boss-man** [comment]
It works. But some sensors are still missing, and yes after a while I also see the map is missing, but a simple reload of the integration fixes it.

**Comment by shred86** [comment]
Just realize this integration is still in early development. There's an [on-going issue opened](https://github.com/humbertogontijo/homeassistant-roborock/issues/41) about disconnects.

**Comment by mirkochip88** [comment]
Seems fixed now

**Comment by tubalainen** [comment]
All good - Just installed it and it works great with out "Emma", a Roborock S6 MaxV.
![image](https://user-images.githubusercontent.com/26795429/210773049-e00c2867-5f55-48d1-8c27-be97132cbb0c.png)
