### ISSUE TITLE
vacuum_clean_segment not available

### ISSUE THREAD

**Issue by etlon** [humbertogontijo/homeassistant-roborock#8]
I get the error message "Error calling the service vacuum/vacuum_clean_segment. Service not found." no matter the vacuum platform I use. Sadly no other error message.
I am using the lovelace xiaomi vacuum card.

**Comment by etlon** [comment]
I guess this is a problem of the lovelace card, not this integration. Closing

**Comment by humbertogontijo** [comment]
If you use "send_command" for the card platform and change the id of the rooms from text to numeric it should work

**Comment by etlon** [comment]
Working perfectly, thanks!
