### ISSUE TITLE
Current error sensor shows state of Unknown

### ISSUE THREAD

**Issue by shred86** [humbertogontijo/homeassistant-roborock#86]
**Vacuum Type:** Roborock S7 MaxV Ultra
**Country:** United States
**Firmware Version:** 02.56.02
**Integration Version:** 0.0.17

The newly added current error sensor is showing a state of Unknown. I noticed the native value is `0` when there's no error, and there wasn't an entry in `en.json` for `0`, so I added it but it's still showing up as Unknown.

Also, just a thought but instead of a sensor, what about exposing something like this to the vacuum extra attributes? It's essentially what the [HA dev docs](https://developers.home-assistant.io/docs/core/entity/vacuum) recommends because there is a vacuum state for `STATE_ERROR`, and the extra attributes are intended to be for "information that further explains the state".

**Comment by humbertogontijo** [comment]
This is becoming a sensor just for translation purpose(Only climate can translate extra attributes as of right now). Unfortunately there is an open issue on homeassistant core for a translation function which is not implemented yet. But I will translate the value integration wise, while that is pending

**Comment by humbertogontijo** [comment]
I didn't check using the error property. I'll check if the outcome is better than using a sensor

**Comment by shred86** [comment]
Fixed with [release 0.0.18](https://github.com/humbertogontijo/homeassistant-roborock/releases/tag/0.0.18).
