### ISSUE TITLE
Roborock mqtt client disconnected (rc: 7)

### ISSUE THREAD

**Issue by aaronpowell** [humbertogontijo/homeassistant-roborock#92]
I've just upgraded from 0.0.17 to 0.0.18, and while the 0.0.18 upgrade now has a lot more sensors, I'm finding this error spamming my logs: `Roborock mqtt client disconnected (rc: 7)`, and the device is going to `Unavailable` frequently.

The message in HA's logs doesn't seem to be overly helpful:

```
This error originated from a custom integration.

Logger: custom_components.roborock.api.api
Source: custom_components/roborock/api/api.py:179
Integration: Roborock (documentation, issues)
First occurred: 10:27:29 (55 occurrences)
Last logged: 10:31:25

Roborock mqtt client disconnected (rc: 7)
```

At the time of writing it's said it's recorded over 160 instances of the error.

The robot is presently docked and charging after having done a vacuum this morning.

What can I do to get more logs/diagnostics to work out the problem?

The robot is a S7 MaxV Ultra.

**Comment by humbertogontijo** [comment]
Have you clicked on the configure button -> saved and reloaded the integration?

**Comment by aaronpowell** [comment]
> Have you clicked on the configure button -> saved and reloaded the integration?

I did prior to restarting, and have done again since restarting.

I was going to try deleting/re-adding the integration, but wanted to try and provide some diagnostics before I "turned it off and on again" 😅

**Comment by humbertogontijo** [comment]
I found the issue. Looks like it starts after you reload the integration. I'm looking into it, for now restarting HA solves it

**Comment by humbertogontijo** [comment]
Version 0.0.19 fixes it

**Comment by aaronpowell** [comment]
Thanks for the speedy work, updating now.

**Comment by inertia666** [comment]
I have this exact same issue on a new install of HA and latest 0.0.27 version on the integration.

 [custom_components.roborock.api.api] Roborock mqtt client disconnected (rc: 7)
 
 If I try to start or stop the vacuum in HA it will work sometimes and other times not saying it failed to publish the service.
