### ISSUE TITLE
Determine which map was used

### ISSUE THREAD

**Issue by aaronpowell** [humbertogontijo/homeassistant-roborock#93]
I'm in a multi-floor house, so we have multiple maps for the robot (S7 MaxV Ultra) and I want to setup some automations to warn me if different floors haven't been cleaned after _n_ days.

Is there anything in the attributes that can be used to work out which map is the "current" map/last used map, or is it the sort of thing you'd have to track with helper entities?

**Comment by humbertogontijo** [comment]
Use the attribute map_status. Looks like the formula for the map_status value is ((map * 4) + 1)
https://github.com/humbertogontijo/homeassistant-roborock/discussions/49
